apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./capacitor

  - ./net-system/namespace.yaml

  - ./net-system/ingress-nginx/ks.yaml
  - ./net-system/cert-manager/ks.yaml