# Cilium - eBPF CNI
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  type: oci
  url: oci://quay.io/cilium-charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: true
    k8sServiceHost: devops-control-plane
    k8sServicePort: 6443
    gatewayAPI:
      enabled: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    bpf:
      masquerade: true
    ipam:
      mode: kubernetes
    operator:
      replicas: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
