# Flux GitRepository and Kustomization for tenant apps
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: ${TENANT}
spec:
  url: ${REPO}
  ref:
    branch: ${BRANCH}
  interval: 5m
  timeout: 60s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: ${TENANT}
spec:
  sourceRef:
    kind: GitRepository
    name: apps
  path: ./
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  force: false
  serviceAccountName: flux
  targetNamespace: ${TENANT}
  postBuild:
    substitute:
      NAMESPACE: ${TENANT}
      DOMAIN: ${DOMAIN}
      GATEWAY_NS: ${GATEWAY_NS}
      GATEWAY_NAME: ${GATEWAY_NAME}
