# Flux RBAC for tenant namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: ${TENANT}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux
  namespace: ${TENANT}
rules:
  - apiGroups: ["", "apps", "batch", "autoscaling", "policy"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: [httproutes, grpcroutes]
    verbs: ["*"]
  - apiGroups: ["source.toolkit.fluxcd.io", "helm.toolkit.fluxcd.io", "kustomize.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["cert-manager.io"]
    resources: [certificates]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux
  namespace: ${TENANT}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: ${TENANT}
