---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium-system
spec:
  url: https://helm.cilium.io
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.5"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  values:
    # --- K3s Integration ---
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true
    
    # --- Native Routing ---
    routingMode: native
    ipv4NativeRoutingCIDR: "10.42.0.0/16"
    autoDirectNodeRoutes: true
    tunnelProtocol: ""
    devices: "{eth+,wlan+}"

    # --- BPF & IPAM ---
    bpf:
      masquerade: true
    ipam:
      mode: kubernetes
    
    # --- L2 & Gateway ---
    gatewayAPI:
      enabled: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    hostNetwork:
      enabled: true

    # --- Operator & Cleanup ---
    operator:
      replicas: 1
      unmanagedPodWatcher:
        restart: true