---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium-system
spec:
  url: https://helm.cilium.io
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.5"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  values:
    k8sServicePort: "${k8s_api_port}"
    k8sServiceHost: "${k8s_api_server}"
    kubeProxyReplacement: true

    routingMode: native
    tunnelProtocol: ""
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: "${pod_cidr}"

    devices: "eth0 wlan0"

    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv4PodCIDRList: ["${cluster_cidr}"]

    bpf:
      masquerade: true

    gatewayAPI:
      enabled: true
      enableSecretsSync: true

    l2announcements:
      enabled: true

    operator:
      replicas: 1
      rollOutPods: true
      unmanagedPodWatcher:
        restart: true