---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium-system
spec:
  url: https://helm.cilium.io
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.5"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  values:
    # K3s Integration
    k8sServiceHost: 10.43.0.1
    k8sServicePort: 443
    kubeProxyReplacement: true
    ipv6:
      enabled: false

    # Native Routing (The "Hardcore" Path)
    routingMode: native
    ipv4NativeRoutingCIDR: "10.42.0.0/16" 
    autoDirectNodeRoutes: true
    tunnelProtocol: "" 

    # Multiple Device Support
    # This tells Cilium to attach BPF programs to BOTH eth and wlan interfaces.
    # The '{eth+,wlan+}' syntax handles eth0, eth1, wlan0, etc.
    devices: "{eth+,wlan+}" 

    # BPF & IPAM
    bpf:
      masquerade: true
    ipam:
      mode: kubernetes
    loadBalancer:
      mode: snat

    # Gateway API & L2 Announcements
    gatewayAPI:
      enabled: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    
    # Allows Gateway Envoy to bind to host ports 80/443
    hostNetwork:
      enabled: true

    # Lean Mode
    operator:
      replicas: 1
      prometheus:
        enabled: false
      unmanagedPodWatcher:
        restart: true
    hubble:
      enabled: false