---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.x" 
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  valuesFrom:
    - kind: ConfigMap
      name: cilium-hubble-settings
      optional: true
  values:
    # --- K3s Integration ---
    k8sServiceHost: 10.43.0.1 # K3s service IP
    k8sServicePort: 6443
    kubeProxyReplacement: true

    # --- Robust Network Mode (VXLAN Tunnel) ---
    # This eliminates "unable to determine direct routing device" errors.
    routingMode: tunnel
    tunnelProtocol: vxlan
    
    # Let Cilium auto-detect the active interface (WiFi or Ethernet)
    autoDirectNodeRoutes: false
    
    endpointRoutes:
      enabled: true

    # --- Load Balancing ---
    loadBalancer:
      mode: snat # SNAT is significantly more stable for home routers than DSR

    # --- IPAM & Outbound ---
    ipam:
      mode: kubernetes
    bpf:
      masquerade: true

    # --- L2 & LoadBalancer Pool ---
    externalIPs:
      enabled: true
    l2announcements:
      enabled: true

    # --- Features & UI ---
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
    hubble:
      enabled: false