---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hydra
  namespace: ory-system
spec:
  interval: 1h
  dependsOn:
    - name: kratos
  chart:
    spec:
      chart: hydra
      version: "0.60.x"
      sourceRef:
        kind: HelmRepository
        name: ory
  values:
    maester:
      enabled: true
      image:
        repository: oryd/hydra-maester
        tag: v0.0.40
    secret:
      enabled: false
      nameOverride: hydra-secrets
    hydra:
      automigration:
        enabled: true
      config:
        serve:
          public:
            cors:
              enabled: true
          admin:
            cors:
              enabled: true
        urls:
          self:
            issuer: https://hydra.${cluster_domain}/
          consent: https://auth.${cluster_domain}/consent
          login: https://auth.${cluster_domain}/login
          logout: https://auth.${cluster_domain}/logout
        oauth2:
          expose_internal_errors: false
        log:
          level: info
          format: json
