# Encrypt with: sops -e -i secret.yaml
# DSN uses postgres admin - password must match database/postgres/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: hydra-secrets
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:RJ+Dk4NaWdqUV3MqTCx6SryOIhA78SAdnjh2v8ZeiFw2pZ9PEog=,iv:mE1oQ1fbe9tUlMwijxWdwSCA7SEb6im2Bc+QHBmrRWA=,tag:0uU2EbVnHtzI5kP005Pc3g==,type:comment]
    dsn: ENC[AES256_GCM,data:/csSGPS0zzdYoE7I8brFEZkCIx9gcO6siUSXapAqgIoagj3lxDPbYAKi/6LrGsNrIBXPxjbwtb5Z85/J6PcvajpZBZAniDn83piBjmF/L9j/GKhQEHFBMamuNXsBuEjvbTbufBekeL40DoUz12P+KN3OZZ9PyPNW3cYggMM32fM0ZOI0SJtmSB83GLK9dc58vfkrptU2Ao9L2+Gq,iv:Qh023FR5MAuY86bMCbNYK2dWEA7aLU3DZEcmIYKZWQg=,tag:TyVolJf7hcccRG4AG43+zA==,type:str]
    #ENC[AES256_GCM,data:k1cWIzS6rGuFzfMeVnRuMaOwhaoNMJ0P3zYmMLaa5lJJIFpq7yC4UFXGS1o8WjMRkzFdspUEyeG6YA==,iv:l94QlK4rjEI2ly4G51UV+d//1DS/o1N4KwBaoxhVVzs=,tag:wkx53TGhQCSw966vmQtPfw==,type:comment]
    secretsSystem: ENC[AES256_GCM,data:LkSB7jW4zpW+c0i0shqw/3lMlTeHx8tFgnBYSG9Tn1MtiBZSzCKpdkQV8RKVyw2wNUHaklfQtvFseCbUWAGesQ==,iv:wgrcFZTizy96s3m4cnk6GjeV8DD4iYQmfMZD/rhOIRs=,tag:stAog/1lPAGMNkjl0/aZVg==,type:str]
    #ENC[AES256_GCM,data:0kzF+R2DpxEJdRrCEHVRguw3CWRG9c9Aj8bK3VSL3uT7XREWOuVANRMvIPeVGYyDUZfvO8LnXzHT,iv:F4wl4YchfUS63DCQB0Y2Pym1IRg0EQDLFJ62Y2ptSwA=,tag:QIxqV2qLE1DkDfLb9BjPnw==,type:comment]
    secretsCookie: ENC[AES256_GCM,data:uAJOmuRKAfaTsqlTt4yScoTn4J1VncjzDfam/KlxBqzWE399B9VPATeHP3QYCh/4FdQl90Zti5VBFl5rENKf1Q==,iv:/1eNdM4S3NgRMGkladIQKss/Tfau/MEQ0A6T+zYkL/Y=,tag:WgMUV/S7vIqVIUKpnTzmPg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWjJGZXN3dmFrV2M0WmUz
            ZFdsN05TVkNZUVd0amo0UTlnTnZUb24wVmlZCk9WRlNCSjZYTTdSWDBkWlhrUGJN
            MjlOeEFNdVVud0RXVHg1bmI0U1BIeTQKLS0tIFhjdzJETlV5eFUwalg5MjBNWHV0
            ZURaVlU0WUZ2WW1ITTFSMHdvVC9sL28KASsGE+HDxL3OAarNGpuPP+eNvTBYh4nw
            yoFkwKkXLQzuoRDq9x0kW4vsAYh4uMfAbS+oUhFjc70+CISlS1Ub9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:13:07Z"
    mac: ENC[AES256_GCM,data:k50+wtfJKgbtbHZ8WpJvFcVya7l75abjuMNi1Adrm7YWAATflCtuOi2lJ0w31G9kWkPETo4MIFYMXQRTzkxefQrkZ1LScnaZVojAe1Zxi+xvoRmlfJ3BwbT/ffSLTUaOTt5COv2NZG4dILaJSLU06hKhqoA5B2Y7IKxNv0xAGQA=,iv:yii6fyn0i1RZSmLhZQa8RAByfgIveYP6UiKYvDarlgU=,tag:um1BMuOehnOb1mbfvS4vnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
