# Encrypt with: sops -e -i secret.yaml
# DSN uses postgres admin - password must match database/postgres/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: hydra-secrets
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:o1Rk5ryalQYW6f5KXFOqtaZjePgntCXxlRta42xse9C+Nd2FBmY=,iv:Btkqw8raVRIotL+/Xb2M8znlNJUUI2mXUdWjrweE/xU=,tag:Gdm/doIo78bv5Ws2CcZM6g==,type:comment]
    dsn: ENC[AES256_GCM,data:Qk6bjfEIQyW0bMWvpPmwxicEwnqBaIdtB5XLco8rx7Db0Lg2NslvrmStOIxOHROoVP19W75I/JG4kqRCQHl7/r17gSikw09w93Y0BZXvXjYAJvr7RKWesBORFUCvVLfAZrlssAXb6rWVvkItSa6Rlk7Lj+54iHub/ItHSuhwd1GeXx6Co7bolspdGQ==,iv:sELc64aIltixS6ZVmiyEE536MXl6jk6Ep906mpSPFh4=,tag:0gzpgLNw9ZS58aqVsyENfg==,type:str]
    #ENC[AES256_GCM,data:vmQ1rxLMrwdnav9C3JYFU3mms/Iyg6P/mcIBTp/c91eEPqrHo9FlOe3Z2D/L/o+fQHr884U3TZP1Ug==,iv:htJ+wyg1e3iiX6YYNskW+zJwfHQXAEa4kRDY7D3dEU8=,tag:ZNn0X+GkZK/WLJQHvrtFHw==,type:comment]
    system-secret: ENC[AES256_GCM,data:pGjtAXwE7qJILxgkKNms3AbA/uwhN1b3SpHSZiU3Ca+j21sfh4UT+UeqeL0JM4xQ4D9S6qbKTpwCjnu3r4tcyw==,iv:LwE2oxJ8ODDz9DwMW7qThIJkNlttzJXuc9jrItgmI3o=,tag:6CEz97KJ4c5ITX+EtjLfFg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV3ZybHV0TzlkTVI3OUJw
            VTcxNUczL1U4R3JBOVNUaVdudUpwUCtSdjM4Cml5VmhwbzhLNm15M1pwaWtMajha
            bGhaY21DMTNqemtXMXI3cTAvdGEyUEEKLS0tIFdPdE8yYjB1OXJ5czdadUh5ck9r
            M1ZRcFNrZGtQRUg1cHdVNFZrbzNvd2sKd+cGbOZyEIicORPLwveKdKGFxEiMNivG
            IV13NApbwwVgvvZIHS62K+mtRiAzMTmqXeCjtmGk/PEj2OgKyZRZPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T20:50:54Z"
    mac: ENC[AES256_GCM,data:3EDpbBSRC9nPVK74UhuZS5TomkCPH2FWZDLNDCX5Y+q9CqVAnwB2pDEmz5Hk5yPBkB5amyrk3Ldi24+BuPTTp60zmzXBDHJERG8W8ByuiCOwnHoBaWe5RYV0Syei8I0oHxGBc1Qxwk9PnPeO2ITicCkoOCXJZXo1cM9AVbeTTzE=,iv:X/Yb4vX3ChfzL7JZ+dPEXRuFgJU3yuzizJ8CKoDtX5M=,tag:9+XgR9VTdPXL5v/vHDkVuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
