# Encrypt with: sops -e -i secret.yaml
# DSN uses postgres admin - password must match database/postgres/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: hydra-secrets
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:wgX9nclL8NxLMY8tv1jRFl8In/umkuwhoTsJMajPF8dLyIctllE=,iv:BIMEiqZ0ZwAuPtxemumdtANOw+xE2b9ptAC27y4Kkwk=,tag:1soO2SMNNZoZs5J9JisWuA==,type:comment]
    dsn: ENC[AES256_GCM,data:ts+bDJJ0N6GCE2+LXOPwC4GeJ05/rArkdZr0pDbnsDv6epl9shE1ZGKOI1mJCE3wC27rPPL7kfrfOGHR62cuOM3DoG5W7E9aOsE3XY/+7sBKnVUweupqlhx4Ftw9uX3yn4UBNInHIDckswA50iHh6l7y3DVLA/u5zHdp9Le9XW/sUSXDnYOn45bjDA==,iv:Is10n0FChgWnP7LoqLSfcWiKMITDpSv6Oh/CTUf2SI4=,tag:X59s/aZF7ASCkjLBGw9XRQ==,type:str]
    #ENC[AES256_GCM,data:QCU7MzrHCZa62+/Y2AM5L5/fyBXINtweR2nGhn6dADdgEm41mv3/hYCgZvuiQx1IMri3/lb8D5JDCw==,iv:eHy51WnvTZpWcv5yMioz5ILYx1M9pspQdn9PRAQtE6Y=,tag:o/LNp9AyzYkl1LLAWyYQTQ==,type:comment]
    secretsSystem: ENC[AES256_GCM,data:orWrSiiMkB69kEk4unmsCfXI/SRQzpFNgD6Jw1V//wTc4Z+GLmdMM+sOAuwiPMHjvnGzyc1B03wtE3Y+VA88Wg==,iv:7EvlN7TlpMmwNJhrfP+6zzwpuh6uWQEzpD0T+Euo6UA=,tag:sHN8nTdJLF2I2L1wLRGaEA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIendubUlxM3ZDbU1US1pX
            WmlkNWxEMzQ4SGs5bzhrelZmNzFWVDVMYVZFCnQ5K2dXK0dCaFlMU2tKZmVSaysr
            SWxDMGhyR0R6YjZEY3U4Z2QvZjRMV1kKLS0tIGpqazA4L0gyQVBxL0pENUxwcXRD
            YmN0ZjJzSGpGVVQvTTB6dHp4N3ZYWmsKTzG0NKnWQeXiELb/ocwtJheRWUYynj4v
            AGp9HpMZNA36Zkx3HUwpQhdx7FRaA3Y4nybqcXxvy5ewbOHsJEFZFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:09:57Z"
    mac: ENC[AES256_GCM,data:74OzaupcJfdxwdWfSLQ71oe/+wHF+F3mFBz9m58Ssl7crEsRzis+lYQo9ugemPIJk+vo3/4qQRn9VNMzagpVHa4WEOUB7bvWt44S6gk3aefNDbe/EabDkRYi1RfvF6my0SuYkm3wbGPaXa77nkBvgeJZs5MhDhXwBslORalpd60=,iv:lF7dDE4znwDVs3XeGVeS4J5fRB2RjkTz3OXHrBjOmjs=,tag:BkWhiJCjyFzfK3ElTGmisA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
