---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-controller-kyverno
rules:
  # Core resources (read for policy validation)
  - apiGroups: [""]
    resources: ["*"]
    verbs: [get, list, watch]

  # Core resources (write for Kyverno components)
  - apiGroups: [""]
    resources: [configmaps, secrets, services, serviceaccounts]
    verbs: [create, update, patch, delete]

  # All resource types (read for policy validation)
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [get, list, watch]

  # Kyverno CRDs (full control)
  - apiGroups: [kyverno.io]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: [reports.kyverno.io]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: [wgpolicyk8s.io]
    resources: ["*"]
    verbs: ["*"]

  # RBAC for Kyverno components
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [clusterroles, clusterrolebindings, roles, rolebindings]
    verbs: ["*"]

  # Deployments for Kyverno components
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [create, get, list, watch, update, patch, delete]

  # Jobs for cleanup controller
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [create, get, list, watch, update, patch, delete]

  # CRDs (for Kyverno CRD installation)
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [create, get, list, watch, update, patch]

  # Admission webhooks (for policy enforcement)
  - apiGroups: [admissionregistration.k8s.io]
    resources: [mutatingwebhookconfigurations, validatingwebhookconfigurations]
    verbs: ["*"]

  # Monitoring with Prometheus
  - apiGroups: [monitoring.coreos.com]
    resources: [servicemonitors, podmonitors]
    verbs: ["*"]

  # Events for policy violations and diagnostics
  - apiGroups: [""]
    resources: [events]
    verbs: [create, update, patch]

  # Leases for leader election
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [create, get, update, patch]

  # Update resource status (for policy reports)
  - apiGroups: ["*"]
    resources: ["*/status"]
    verbs: [update, patch]
