apiVersion: argoproj.io/v2
kind: Application

metadata:
  name: argocd-application

spec:
  destination:
    name: in-cluster
    namespace: argocd

  source:
    targetRevision: HEAD
    path: kubernetes/argocd/templates
    repoURL: https://github.com/stupside/devops.git

  project: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true