---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: xonery
  namespace: xonery-ns
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/stupside/devops.git
