---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa
  namespace: opa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opa-configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - oidc-profiles
      - oidc-hostname-profiles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opa-configmap-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opa-configmap-reader
subjects:
  - kind: ServiceAccount
    name: opa
    namespace: opa
