# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: staging
#   namespace: cert-manager
# spec:
#   secretName: xonery-tls
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   commonName: xonery.dev
#   dnsNames:
#     - xonery.dev
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: production
#   namespace: cert-manager
# spec:
#   secretName: xonery-tls
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   commonName: "*.xonery.dev"
#   dnsNames:
#     - "*.xonery.dev"
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: selfsigned
#   namespace: cert-manager
# spec:
#   isCA: true
#   secretName: selfsigned-tls
#   privateKey:
#     algorithm: ECDSA
#     size: 256
#   issuerRef:
#     name: selfsigned
#     kind: ClusterIssuer
#     group: cert-manager.io
#   commonName: "*.xonery.dev"
#   dnsNames:
#     - "*.xonery.dev"