---
apiVersion: v1
kind: Namespace
metadata:
  name: capsule-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule-system
spec:
  interval: 1h
  chart:
    spec:
      chart: capsule
      version: "0.11.x"
      sourceRef:
        kind: HelmRepository
        name: capsule
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
