---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xonery-apps
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/xonery
  interval: 30m
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: false
  dependsOn:
    - name: tenants
