---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xonery-kustomize-controller
  namespace: flux-system
---
# Cluster-level read access for FluxCD and cluster resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-kustomize-controller-cluster-access
rules:
  # Read FluxCD resources (for GitOps operations)
  - apiGroups: [source.toolkit.fluxcd.io, kustomize.toolkit.fluxcd.io, helm.toolkit.fluxcd.io]
    resources: [gitrepositories, ocirepositories, buckets, helmrepositories, helmcharts, kustomizations, helmreleases]
    verbs: [get, list, watch]

  # Read namespaces (for tenant operations)
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]

  # Read cluster-level cert-manager resources
  - apiGroups: [cert-manager.io]
    resources: [clusterissuers]
    verbs: [get, list, watch]

  # Read Gateway API cluster resources
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses]
    verbs: [get, list]

  # Events for diagnostics
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]

  # Read nodes (for pod scheduling constraints)
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list]
---
# Namespace-level full control for tenant workloads
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-kustomize-controller-namespace-access
rules:
  # Core workload resources
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: ["*"]

  # Core resources
  - apiGroups: [""]
    resources: [serviceaccounts, services, configmaps, secrets, persistentvolumeclaims, pods, pods/log]
    verbs: ["*"]

  # Networking
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, networkpolicies]
    verbs: ["*"]

  # Gateway API
  - apiGroups: [gateway.networking.k8s.io]
    resources: [httproutes, grpcroutes, tcproutes, tlsroutes, udproutes, referencegrants]
    verbs: ["*"]

  # cert-manager namespace resources
  - apiGroups: [cert-manager.io]
    resources: [certificates, certificaterequests, issuers]
    verbs: ["*"]

  # Autoscaling
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: ["*"]

  # Batch jobs
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: ["*"]

  # Policy
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: ["*"]

  # RBAC within namespace only
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings]
    verbs: ["*"]

  # Resource quotas and limits
  - apiGroups: [""]
    resources: [resourcequotas, limitranges]
    verbs: [get, list, watch]
---
# Bind cluster access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xonery-kustomize-controller-cluster-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-kustomize-controller-cluster-access
subjects:
  - kind: ServiceAccount
    name: xonery-kustomize-controller
    namespace: flux-system
---
# Bind namespace access to xonery-gateway
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xonery-kustomize-controller
  namespace: xonery-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-kustomize-controller-namespace-access
subjects:
  - kind: ServiceAccount
    name: xonery-kustomize-controller
    namespace: flux-system
