apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: xonery
spec:
  owners:
    - name: xonery-admin
      kind: User
  namespaceOptions:
    quota: 10
    additionalMetadata:
      labels:
        # This label is the ONLY thing Cilium needs to identify the tenant
        capsule.clastix.io/tenant: xonery 
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
  resourceQuotas:
    scope: Tenant
    items:
      - hard:
          requests.cpu: "4"
          requests.memory: "8Gi"
          limits.cpu: "8"
          limits.memory: "16Gi"
  networkPolicies:
    items:
      - policyTypes: [Ingress]
        podSelector: {}
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    capsule.clastix.io/tenant: xonery