---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    flags:
      logLevel: "info"
      logFormat: "text"
      updateStrategy: "eventual"
