---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  path: ./tenants
  interval: 5m0s
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: system-network-configs
    - name: system-core-controllers
  sourceRef:
    name: flux-system
    kind: GitRepository
  wait: true
  prune: true
  timeout: 5m0s
