# Kyverno - Policy engine
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  type: oci
  url: oci://ghcr.io/kyverno/charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      version: "3.3.x"
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    reportsController:
      replicas: 1
    cleanupController:
      replicas: 1
