# infrastructure/network/cilium-global-policy.yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: global-cluster-base-security
spec:
  description: "Core Connectivity & World Egress"
  endpointSelector: {}
  egress:
    - toEndpoints: # Correction du sélecteur DNS
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEntities: 
        - host
        - cluster
        - remote-node
        - kube-apiserver
  ingress:
    - fromEntities: [host, remote-node, cluster]
---
# CoreDNS Upstream DNS Resolution
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: coredns-upstream-dns
spec:
  description: "Allow CoreDNS to forward DNS queries to external resolvers"
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
      io.kubernetes.pod.namespace: kube-system
  egress:
    - toEntities: [world]
      toPorts: [{ports: [{port: "53", protocol: ANY}]}]
---
# Tenant Internet Access
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: tenant-internet-access
spec:
  description: "Allow tenant pods to access the internet"
  endpointSelector:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  egress:
    - toEntities: [world]