# PostgreSQL admin credentials only
# Encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: database-system
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:8TXXLSudLkI9daRUI7tKR0wWjWw830JPp+P7waHj1Wm2uf5hY7HQqFwf+8w=,iv:2O6Qv709g3yq0R+YF2JzRsInCYzxglyOgfngRJXRIdQ=,tag:+FQ6jmhXH9NFr08YYUa6AA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR3RiTW5rQ3pGcUt1N2li
            THZEak9DSVcyMG4zbHF0a085OUtIYkRqdXk4CmZjaWJmazE2UTV6emZBdlFXV0tX
            Uml4L2VZdXVmbTl2MFVHRFM2Zzdydk0KLS0tIDUzTG56Y2J2cG5xRlc3M3BBRHpj
            akd3MW5pN2RrdkF1VzNXUnBUNXlxd3cKiSLyy9E9ZrE9Brz3d+8i8afFs7wHgwcT
            K0JWcyNByXpk/eRp5QkktlMYFK5UUTC9R3Jwl3IoeJo0rpJ0ybM5Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:59:33Z"
    mac: ENC[AES256_GCM,data:jzdByNBCaWKJxsE+GkOPYUyb/wy9+0ACCUAo7dEQb3cfLm/3bfwbCrTL9EDDRYLEESgIHb4heDyrMB07AQBwRwg/+OoZW5iIGkO9ndFkQxKlcG42+04UtwMgqQPxIAjvDzxLniuKf6lOdXoU9V+mNRNwyfj8myDWUhF0CzususQ=,iv:PbSqpYbiTvgicMCiGC+Au1Pf7vEaftHdq/oMtp5jMnQ=,tag:1eROcQ9kW/gZlCpIH5QbNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
