# PostgreSQL admin credentials only
# Encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: database-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7eLLBaEARDjKDdSsqFf/jCcSd1L961dJsBeQ9dZuGJ9Wof7VT92ATlk0fqW9KDRFFaBvmbU/YxCz6WGnVgXQzg==,iv:r4VRqpy+qrNJyZiwGRpG5J5YOkVeXm5lgmh4vbiKLqo=,tag:naTkOhIehMvoa+dfpvzzaw==,type:comment]
    postgres-password: ENC[AES256_GCM,data:T98RYu13d3CAx+cKuLSmg6o0dz+COMTgV5TisRtSZoAUqmlFB8MI9ksdD4xp85Lxm9co2TuRwbYIgf7L+wwGUA==,iv:MpGPk+g/cu3oUQ8xeH1EGBCTW038xyFbjAFyIvN1y7Q=,tag:sHfeZiF5mNWFVqPDEwkutw==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbWU5YXRqM0k0c0NSZDNE
            bjJhbXVXMUNNY2w2RjNqQ25WREFGVGR1bUc0CllIM2dYMldVUVVPakt5M2hiRlpt
            RWJvc2VYelhTeExnQk9admxpNllrWncKLS0tIHhnOURRSWZxR2NuaVljeEp3bHdu
            TS9mdXMvcmtxbzI2SmFXcXdodDZDZDQKsaAisNlkFKgbqU7IMO+z9FiwxeLUVsYh
            5gf9Gd8ocbT+nVjPzpkbCSeuJbKS+KDGn+OD4RAQfYEOUy6EtkhbVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:43:47Z"
    mac: ENC[AES256_GCM,data:O0k44rg6uRxXo957HFJ/9KFNoVXfVaAKS5KBbxQxyN38yUHYByO2NDoeeTfLCCDvLnHrsM9YXyaqscTF8EYGYzKw2mp9y+qeQdm3jCKtDzKSg47n18mqRC5Sfxpc9z7l0TspF+6RlgTK2jLPZMolNc3LS4OlfwEEPG5gUOTRnYQ=,iv:y/Fks6j/EcQFE9hxpLMX/NPqZi4C9paEjP1q6jy4yYY=,tag:i7MVWZ3AiaZVJ5g55yi0QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
