# PostgreSQL admin credentials only
# Encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: database-system
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:yngqGCrP4E32kdRSf55jcN6Qrb7na9yVl2EjvFD3AY/fkD5Apk/WkgTm7NI=,iv:g52GbZ/SBpWN+46k6vV1a1u/AaBT72uk9YtLrJ5VbuY=,tag:TEirspAvlEyVo5OvY+KxSA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTVNBRC9SOUk1WVFUZVk3
            VjRWTkxzQTJiSmxwZ2VVTTlpa0lEQ2tEMjB3CmkxLy9wUmthYVdydGlsOUxiTUI1
            Y1UxQ3RmaXBjckFSWXJzUE44TU9hOHMKLS0tIEV3VkVjTXRvcXR0MFNuRmlEMHpn
            aklpclBVQkFNTmhFUStoUEVCYVVGS3cKzb11E2XAxN4OitH83zSviTGPHppuR4b3
            gXxl2qWqV1rECJkueTdhpzTCinV3c0WqYU5ZX50btnVO7hNinRRP0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T17:42:59Z"
    mac: ENC[AES256_GCM,data:fOyurwEMLYlrswwIR/hCoDl46TB4lIzxNFvX9amK5mJpOpdb9K6hcWIiOhYkzBIqVa6KaXZkT9SZIA4EAKDh+ZK8bOgNRAsxTAk8GBeXkzPVmeCzBP8H8340Y1ab0vDI6JuzyR7bTzigOBOg3yh1gnqY8oCAYpjQmGqtcwsM1YY=,iv:pc2BYJ4XmayjFVHZfn4PISaEYbOaQ5TNVxB0kapxqos=,tag:4FTQZFJJpxV2KOmweVoS6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
