# PostgreSQL admin credentials only
# Encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: database-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kTUrNexj246KJtVNWdV4IjelevWsosfRY0lj07FzNpHs0w3J8ukVTqE5URYjg2UuMkaUUDgO88D9ZUyg6abJKA==,iv:sJjaVamlV/2jqokTQ/qUmdYavVpBwoHjsTCRjGbxqec=,tag:QKRxTCOuyqo4vjeV8i2X/Q==,type:comment]
    postgres-password: ENC[AES256_GCM,data:IKobVZj6ruuPtdI5+S7uf8qztHRsEojMfbQj63eG4Yk0Kw/6VaeCU27PsTkbNk4tETTWM80nMviG8z+3H5arnA==,iv:pYN8S1fAYmrGgj23Z8P/vAmqhww4Yn7UaEGM/sDRZrc=,tag:NqKoJ+yT8E2uGQG24Nhmfg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UGJsWVF5dkx6dWRxQThv
            a3d0YzJheGdrS1UzSmV3dFEvZHdkME9QYUNZCnRwNGZKMnVCQ2Q3bGZEczBDT3A5
            OVpRUHdTZ1ptTitEbmdLRXppeVNYL0kKLS0tIG53SlRVTVprL0Z6UkVQM3ZIdHJ1
            TnNZdTk0dUp3SkhWdkxLdFRvOWU1WTgKxcU3byfN9hzuNntPJRgBIE5q5Rw02vM1
            ojTwATfbcLrqaqIgMS3fPVBfvaPd8rI4YJV6D26FH0jr+fF4JmLd3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:58:48Z"
    mac: ENC[AES256_GCM,data:LSKmFg+qhUANQq5Byueec1IHm46PjjoXhpZ/eXk8TCK/NiL9WDo6HejDaMdmF7HrStHO58gUARUDJvMB9my9LaYjWyyayOU3Cq0Q/t6uXWvUIG9Sr7TuTmiwFMOvp2yVf0/H8w2OWH0yjbM+3NFXlPVoHtOsvO8hw2nC0UivIic=,iv:kgUeqEHMvwcQVFRfdgqX5+/+WtWE1o1mV8dJU/A71nw=,tag:il5yt8NpakLgluf/MATORQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
