# PostgreSQL admin credentials only
# Encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: database-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:wrtAX6TiVej8JdxF0Z/7J9M1nVdGoLIBV2mH29ZKADNvL48scIhDJHAdtSZCmCzWoZ2u1qPtcv/LeUL0SYBHvA==,iv:cSZqq5K0oSWRK7lSeExCasZ37yOmZsPrHcAITWsgTaM=,tag:ZYk27tf7MQ2B+2ldwMbPlA==,type:comment]
    postgres-password: ENC[AES256_GCM,data:ikkuzpwdelwC/pAulCAfiDJMNlaPAUmIUldetd5wbc+PeAGcypzSd5vlo5NwD0MmxLpsX7UZB7pDrUmzqGbznA==,iv:7BjuecAlZ1Yb+/lRvojA3L7m6wlNtC4tF7MuYrCW6EM=,tag:1bbme+t5CSZ8xmVvV+0O6g==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a3dXZnVTWFJSNHE3WnAx
            bUdpM04rZVVCNnM4NWhtNWFGR2ZJVlNkWFRNCjVWUUt1cjF4Z1BCdGVQeDJOVUx3
            ci9Oc25nNFQ2SjdyVWIzS0gyeDV1WTQKLS0tIDFrczdrOFdwMGh1RWluQS92c1Jh
            NXdQQ0Z0ZWp4RUg1N0ZDVXVqR0paV2cKjFnY8efqSF8qtjC1rXMqWMWbE94DgMEJ
            C0iRJQBPly1vhMgH1Lal1QqoMzqKVNfn3rI+rSlW1S2EUWu3wgDGjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T20:39:36Z"
    mac: ENC[AES256_GCM,data:xKEuvecVrO/7862/nuvhGMtlKdIMimxfNxHj3KeWDdZk9PMShO+ELOcSCQ0aj/X7pBX7uILR6HrL2bBH8rsaX5EVZsKoG73K07uAwuvlVxjaCFVMaKUB9j9Ma+F/tOZMPhrQVGnc2CXCUV7T5gncPFbnqRZuUuLzRLVcL2cabi4=,iv:NkXmVUbPwT2FuR8FC4DawoQIrX1P48gcRI+L/6D9gLc=,tag:cFd7PWnVR9VfkBfE7hZCYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
