apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portainer

metadata:
  name: portainer

resources:
  - namespace.yaml
  - account.yaml
  - rbac.yaml
  - volume.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
