portainer:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
    repository: portainer/portainer-ce
  service:
    type: ClusterIP
    httpPort: 9000
  ingress:
    enabled: true
    hosts:
      - host: portainer.xonery.dev
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
