---
- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  changed_when: false
  ignore_errors: true
  register: k3s_version_output

- name: Set k3s installed version
  when: k3s_version_output.rc == 0
  ansible.builtin.set_fact:
    installed_k3s_version: "{{ k3s_version_output.stdout_lines[0].split(' ')[2] }}"

- name: Download k3s version artifact
  when: k3s_version_output.rc != 0 or installed_k3s_version is version(k3s_version, '<')
  block:
    - name: Download k3s install script
      ansible.builtin.get_url:
        mode: 0755
        owner: root
        group: root
        timeout: 120
        url: https://get.k3s.io/
        dest: /usr/local/bin/k3s-install.sh
