---
- name: Run k3s install script
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    # Servier configuration
    K3S_CLUSTER_INIT: true
    K3S_AGENT_TOKEN: "{{ k3s_agent_token }}"
    K3S_NODE_NAME: "{{ inventory_hostname  }}"
    # k3s configuration
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: "server --tls-san={{ groups['server'][0] }} {{ k3s_server_install_arguments | join(' ') }}"
  changed_when: true


- name: Setup k3s main server
  when: ansible_host == groups['server'][0]
  block:
    - name: Copy k3s server kubeconfig
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/k3s-{{  }}.yaml"
        remote_src: true

    - name: Wait for k3s server to be ready
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 300
        state: started