---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  path: ./kubernetes/infrastructure/controllers/capacitor
  sourceRef:
    name: flux-system
    kind: GitRepository
  wait: true
  prune: true
  timeout: 5m
  interval: 30m
  retryInterval: 1m
