# Capsule - Multi-tenancy controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: capsule
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capsule
  namespace: capsule
spec:
  url: https://projectcapsule.github.io/charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule
spec:
  interval: 1h
  chart:
    spec:
      chart: capsule
      version: "0.7.x"
      sourceRef:
        kind: HelmRepository
        name: capsule
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    manager:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    webhooks:
      enabled: true
