# Tenant definitions
---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: developers
spec:
  owners:
    - name: system:serviceaccount:flux-system:kustomize-controller
      kind: ServiceAccount
  namespaceOptions:
    quota: 10
    additionalMetadata:
      labels:
        capsule.clastix.io/tenant: developers
  resourceQuotas:
    scope: Tenant
    items:
      - hard:
          requests.cpu: "8"
          requests.memory: "16Gi"
          pods: "100"
  limitRanges:
    items:
      - limits:
          - default:
              cpu: 200m
              memory: 256Mi
            defaultRequest:
              cpu: 50m
              memory: 64Mi
            type: Container
  networkPolicies:
    items:
      - policyTypes: [Ingress, Egress]
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except: [169.254.169.254/32]
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    capsule.clastix.io/tenant: developers
  containerRegistries:
    allowed: [docker.io, ghcr.io, quay.io, gcr.io, registry.k8s.io]
  serviceOptions:
    allowedServices:
      externalName: false
      loadBalancer: false
      nodePort: false
