---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 1h
  dependsOn:
    - name: kyverno
      namespace: kyverno

  chart:
    spec:
      chart: kyverno-policies
      version: "3.3.x"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno

  values:
    authzServer:
      enabled: true
      replicas: 2
      service:
        type: ClusterIP
        port: 9081
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
