---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      version: "3.3.x"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno

  values:
    admissionController:
      replicas: 1
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1

    backgroundController:
      enabled: true
      replicas: 1

    cleanupController:
      enabled: true

    reportsController:
      enabled: true

    features:
      generateExisting:
        enabled: true
      policyExceptions:
        enabled: true
