k3s_install_script_url: "https://get.k3s.io"
k3s_install_script_args: "--disable-traefik"

k3s_remote_kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

helm_stable_repo_url: "https://charts.helm.sh/stable"
helm_script_url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
