---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cloudflared-policy
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  egress:
    # Cloudflare Tunnel connections (port 7844 primary, 443 fallback)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "7844"
              protocol: TCP
            - port: "7844"
              protocol: UDP
            - port: "443"
              protocol: TCP
    # Forward traffic to Gateways (HTTP/HTTPS) - using toEntities: host for LoadBalancer IPs
    # toCIDR doesn't work for cluster-managed IPs (both sides managed by Cilium)
    # Public gateway (Cilium): 192.168.1.240:80/443
    # Private gateway (Envoy): 192.168.1.241:443
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
    # DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
  ingress:
    # Metrics and health checks
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "2000"
              protocol: TCP
