apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
    labels:
        app.kubernetes.io/name: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:/eOTJROn2lUecxh5FN1V01N9rSXFD5YTpmbr+PflMVRff+8EVpQE6WdG0YWJyBAMTiRMPOx9UJbUdEOJXHfbwR5NC3FuBpSO5aiSRcGSOaJkiq9+5yLyP7itQ6sUnv3wm8Y/Va3B5UjZFIARIUOTIMrz7TufNppypv9z0t2dSMo5j5UX+oB7dH25/O938yTJWtLCu31OHMkTgjmHI2WQMcy11jC2GSqq270aH6wnbrbfclEwCixn8A==,iv:ARmRa0Kq0OZzUwvMSeMusCiVyQ676lXspWPQh/2abaA=,tag:pF46EWz/9vJV8sY8firz4Q==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNDlOTVNPTG12cTd3STVE
            cTR3aSt1WmFFaVpIRGxUajcrR0R4VnVialdBCkMzL3lVelZCekE0ZStZUXpENkcr
            RlcyQXpjakJFUGlkUkhnYmpNcjNVRDQKLS0tIFJtYktxeCtDTmtHS0lqTWxuSlJa
            RXJ4WDJoU2kwbTN2bHB0TllLTWZlTzgK7IxS0DHaK1vWc8SoJIEPoU9R4i9D3kbR
            QeZ78m2etvZTKjwYAzhDgQitla8kLjqFyReaYKQRJhv5VN1ulbjn4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T20:39:37Z"
    mac: ENC[AES256_GCM,data:6LKrbPg5X/gQ36wrzu0bd8jydT/fydOcyi4CIyxanPc1zLGfgsYmjTHyNUfuQKn+rd62shoLitGKRHIFVGA+m/ccxgsXMsjX8iFAAiQKzoCagim0EIsbd/tgMsFcfN0MfYhv+nhrMyC8P0stMADpNsdp0+7zRpvaliEN2QenNdU=,iv:bPvp8Tz/bCbaehM2NwS7mjBaOqUET7xek2o9Xf/YXj4=,tag:7u+P9JZ9rji1fp38hPb4Vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
