apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
    labels:
        app.kubernetes.io/name: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:/J9o/z4lUEPRkH2naOf+sifaOabUhncx68Ddjo6hOtnfnjYDD0OvjhBkDVFF7zwaEIQ977Pp1yIC79ju1+gy2pMLCsTkZwrpmN3R7gE0OyTDSk5KrUImYtJouMMj1Yg7VVeeKFCj8zIidRCeNeyl/7m1AwMfNofd2AYFYmFb5M66bypgcp5hKRTrPwCDnBj1CCW4hUD0kocVd/8dQCSZtMD9GNF9RUJavHjK4MZ/cZZuxAkGau/B5Q==,iv:aRfwy8a4+5VPRweeyQBUDTEKIbQwb1Jqt6JO+Fq1sXY=,tag:BH01Aq0EuZUMWFFB8TR+uA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNytJS2FHOFFCNTdkbDFs
            M2RKVTlsYTI1M1R4ZnBCcXlPR3NNVzhzR3lFCkhuU0tYQ2lYQ2pTQUxxZ0NmYmJU
            MlppRkJXNVRvTTNoTWh0VzhIQ0xnRmcKLS0tIDYvOEtOV0hJRmZGOXVVbk9QcFNB
            U3dPMjJnVGFISG5PMTlhRU1LbXI5MjgKrYmqKLuv+snZukK2hBO0PWDQmwBiaoFC
            ZEk+XGrunuCwjv1bGJGZdGgmlJ1W6RET4/89iG2iwUtjRGcZFy598A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:30:52Z"
    mac: ENC[AES256_GCM,data:yBU2uY5KA1TyF+pACmfOYaHjy3K8GeogXZe5z7Z7IrJlfjkJrxCbUv6TshmuProRUs+MgDLxFHJ/AMT57QaNx4abUEIQoLeOYsruTjGrMsX8Sinjlq+7lGzgr4xlhdO9rUUmOBy+j3/2a67cMabultovHmUO82CedMvg3woaWJk=,iv:FkMCXmJkJA9mRK4Ee/xUdFq4Jqj+kQyvAxo2JSBWGoA=,tag:ayi0h25EdLnLyMZzuaSmHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
