apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
    labels:
        app.kubernetes.io/name: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:DxCVq6cBtT7j0Anhv5bZV18N5vMiSuuQKC9thdww655MV0TDw33orYnvgQhb+/HxhLlKVRr43F2Zj9aNDpKxIBOq3UrQ/hVR8jmwVoPFV1r7do/rm5A8pueqn+uzaW70wm83h90pTyHSh6dR8/7AGWAnIv3kyyTeNGBc4jNvi9UK0KRErUJJKVxyVyKjjxDG9SEt+9z7k4kjha4msv9T3fS2Qy19pXD6ckx8W6TxH6ovhuocMbSbqQ==,iv:1qP/oZrrN8iOiKT0uPOTHUBHGxLusBLovBKjpUclFeA=,tag:aPN1OddGkizVeBptiAE/Bg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVUJvR1pIb2FhMVI4NEtX
            TjdCVE9uaVU5MGZveXBCcXBMdzdKdGxOQzBvCmFqWi9SekdkYkFrTG5KWVpYOW9X
            emp4TjV4bXZRV0h3V3Fjb25UdnhzSUEKLS0tIGtvb21tSzNzcTBGaHF2Q1VBT25K
            cDJGWGppMkpQSENsVUdLZFRjVTE2eUkKEdMz3HF8iW8wWDMMTp6OH/F5TCRzUetk
            8Z01bV5oaWkDqkP577VC/mTd552q8NQfGQqab+YQdXvhYaEAJCTJAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T13:25:42Z"
    mac: ENC[AES256_GCM,data:7WjlMpaucccLD4+EjEg1+I6DJcbGkE1u2uVW5Sjt3z2JlPEOyrsKxmE0RYVSgPgfpUhI6uq3iiUQQ/ZYWznlkzbbmMwSl/Rs/m8h5Q4a8Y0eOnAis829QM9ZGVWDcik/+MZldLzvO0907vCwTpCSjD463/2yFv/sn5gfeneIyS4=,iv:PyV71QBbzDpGqYE/n7YZtTnlC6sv17zs4wpBr6t4Cus=,tag:T2YSoJ84+FwkPs67AuJ72Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
