---
- name: Download k3s install script
  get_url:
    url: "{{ k3s_install_script_url }}"
    dest: "/tmp/k3s.sh"
    mode: "0700"
  tags: download_k3s_script

- name: Install k3s
  shell: "/tmp/k3s.sh"
  tags: install_k3s

- name: Manage k3s configuration
  block:
    - name: Fetch k3s config
      fetch:
        src: {{ k3s_remote_kubeconfig_path }}
        dest: {{ k3s_local_kubeconfig_path }}
        flat: yes
      tags: fetch_k3s_config
