---
- name: Download k3s install script
  get_url:
    url: "{{ k3s_install_script_url }}"
    dest: "/tmp/k3s.sh"
    mode: "0700"
  tags: download_k3s_script

- name: Install k3s
  command: "/tmp/k3s.sh | INSTALL_K3S_EXEC='{{ k3s_install_script_args }}' sh -"
  args:
    executable: /bin/bash
  tags: install_k3s
