---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 1h
  chart:
    spec:
      chart: headlamp
      version: "0.39.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: headlamp
      namespace: headlamp
  values:
    config:
      inCluster: true
    serviceAccount:
      create: false
      name: headlamp-admin
    clusterRoleBinding:
      create: false
    automountServiceAccountToken: true
