apiVersion: v1
kind: Secret
metadata:
    name: headlamp-token
    namespace: headlamp
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:XnDh9fGc2n8hPsFbxu2yzdy3VkUKNlxr+y815xjlDHlSBQNIV7Zdl2xky+9/sqWQheCg+PLiWpQvkiMa1wq7ayRUWGr7Hu8OeMAuXFRxOAx/LTz7ruzk8PGi423AeRXiLCSRrvH84B5bgHQmIRuzChbD6mHDnKExyaHR/LqmxxT7eDOF8KnlQbANVnXaQB3KeVvDJdNq+vNCtWb5/vUO5KNzKwD0nbE5kCYW+ZdxRY8V9dTjenNF6I/HD7POPq2RALwFlMeuXtKT2tb20NLwxYBwIvvDNNVW6i7fJvHvbzeGRFxsF/q1FeuupYpXgcLJ+qk6co+4hzFc23Myak5mi/HocMAl4sUrCZ06/kCBX8A6AtxuEq+6C6I8P+TIG304FPbo5CUVkyNQS/PIS5FiTersa+iDUdD7btHCFAnxxOmCyKdSrVMT1WQ66JeAoZUErinAhGePHowpJKw3iRJ3PV07IkEQts25/6bNBbvvLQ2j+5cqhX2v2tDpyaWn4qPQ+Do6cL2Fbc/f9BQt+ows6p//CdRaP3hR7JgJyUS+q1uJnh5HZLwCquUoaXN0DYhirGNEd0w1aFmphiNIME2EUzC0m19W2SxFj23xuSp+qbCmwEshPGDsgpFchKYKnNcIelCrDxhXpMjqt6ujwmNvkvBEVBoIfLlG0marFPGP0NNu9FJ8GkCgTOnV/p5sEXTWbRsjW3HQogQlGsPWgX4qbeAT2ao0AEzhnLETZq+uTqV7AMMraj4Jd9GQD6Mx67f55H2cSXqPwksllHGA1q6h39KV3jcAyLOYbhDDBxynO5ppxElN0j+QaDNBELTutUDDoxfOGNCUnoWQ5TW1iWJlT7p5DQ7vlboBBOHKAStm2lE5kHUsUR4kY/g3rI0X8HUVWJ6bb4IkQUNv3UiDZslElYJXqY9BKJ+hlvMrtQNoV2ySjRaoo8gUtrpRGPlly4yJtgN+WDIIDXL0b3ZxEA+U4qwkHxBIyVYBWeuUURW/cn5bRwZ0750tQ5gHKZqgXadaQtxT6JRgSgmujmR3dW7OsM7bGvYvGfI6FrP4le2j8ck1v53mAXU0QHyCcM6k6oQ/Iet+4Yw4yltL3I6vuPajaDWLokDlXMv/iP1gN2tdJLxirUHHDkZhkoIE2X+K/ad6rXciMxQHSwpW1L3QxovEH7a01KNQuNthWEYACWNBch7xM/J5UGWBfKxKgKJ+SmnFntIzjGg0BUG8vixpiRWGQmao+8L7YE+YiUoypOPvSv2+3/MoW4pWpNA1yyF5KjRh,iv:yAsqYkDI9CT8VSfXLaBiJqnYt4W3tTiObCZItfD5elg=,tag:fJnYsaxuZ/sx7ndyAxRNcg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUlpoaW9tTElOZ2xVbUJO
            WVZ2OG5EK00wTXNTQnJ2QXgySktRa2E3bXg4CituNTlHRHpUKzYzdlBzUlEzZ0Vk
            Z0ViMzVNeWt5WTk4bDcwajhFMldwL1kKLS0tIFhYNDRWdVAreUI1SCtSZTB2dzVj
            YjIzU3ZmYm5ESnpXYThvd3N6SE82REUKxEFAm5Ec/B46IGxfhd7Ukr2J8sHF+ZWu
            qySed7sTy4Zb6IdAyL3CT5VVYCGgp2jjfRHeAntHc5NR1+PbNH4VgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:39:31Z"
    mac: ENC[AES256_GCM,data:F7GL1dP5aqzURsx/Qu2AtuSQGHjZk9zdSE4CulNEBXZTy6UhvgHbResZhJs37Wesw1BdJUiGlURZFTbakYu3zjDey3Pzw1Rp93SgS5x5gGq0EpJMpwlVBqr8LNuA08EsN18iH8wlYC0Gv/XaTxg5hEJu/UijbrDQi4fDefG0oOc=,iv:VPf/r96RooX3J5iIeU2P3K4UM59R/kykTT0o3dECATs=,tag:qSzVYcFABPG7TIwFhZDB+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
