apiVersion: v1
kind: Secret
metadata:
    name: headlamp-token
    namespace: headlamp
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:kb/7JIshO5za9uhnfxVYTj/QkP0X7lrQGTz+BbpLchKcstn0H2j06LunS7SY/NWOYIorDOI2YwXJ+z6AEnddsI9q7Awd2j113fGOngYh4MdmrRP1RXo+1LBQHd/52E2+7wvFzXePBnJln8a6ous728L/IR/ohI0i602G8Kj2LKt61Xak6Zx2foJDlE39MekEDjewW0MaNLAguDDg15/uFmbTR6Lpl4zDOGMmX6Pwv6WMeYgUtMuUZGoOMIbp/d4t2kydBCEG07LZIBh+1Tx4sY0uHzf8TsojaEVMrNbjx3nANrx3L6cB2jm44Znzo9gxF+bqFV3zDb6gqsIIx33Nyoq3B3n9ZFUrtg4XzbsshkZ183JPzsHiYtQhpSMGOFWDocONUTwPiTI6wL4eBl4g591jkv03q0EWufi+XRZ8WnFNWNImt0ijbjJb0EN79cCmobMcm7hU9u35cm8P7A+uk8OkW7Nd8IxyjRtZABf5BB3LIoSZkJSnk3CUuwzZhXOvtZ91E/Q78ZJe1oRzQrmVGxXJG0fzPewk1i80e9z7+Hw57VTroMTuww4z6RLgGD879Akit+sRZvRhEzsCuGFZXe2WZF/i/wp58EUSHPLoZG/KvJVVAIXWPQdRogKPoim57r1oYyKfaI5ZnEBmZtPaw63scLjCPIIWts2PidjGCKlPy+tDH0Cv6rr6v+xmYGq51HWSMBajMzYf5eU29kDheKEMX18V+1ggTAiQ/jJDW6dnmTmz+jSZ19Z/JBxqLFR7gFipdDSjN3MBnHKXiXb5h4hk82Li4xEICs2Dk+Ud7kw27+wJtg8eQZoctm8ZjHSdmQLZE6gDCnxecmhyLT7l0a0xblVfqHx9YQGkEVVY4sBMQTq9LwkSqgYJ88oI8TwqW/oA8cLiHQPY2pV8/NKEEFJXxGjtYAk3mi270J0O0/v/qFiQ+vS+QHLEyl4CUCddJNZjXfbVVrewe2OTo/YGfVwWeEUmS4XS5sOiLcZeJbkM7lRhS0BlKjUZ8i8fZZhNf3bCoeZ0vvZ6y4dQt+MjEEQ1KqRgrczxDWKCi/RteaS3QPbirZqBqL6d4/6UEbMUMj/dCJ5LM8hNIzndn06URIg7HGAdvFpBIR5p327TS2A5AJGdTsDCyIxVokkDMUHGuIEmQ7uNR16NS7axGdmp6cEtLpDkDsAUskTPUALFrp8qpwi8RW3NrK7drNfZ44PpOVRuOf6c4444V99e5Yb/fPPkpAGYyCIPqEi+tMFEmlOOLcZ4ww1v9Hd5+fMQQGcV,iv:wzTosu4grJuHZrq5LX1OlGVH74vYpC/Q0deVQs7sDbY=,tag:zgWPv8ChnpZIRZ0m7eC7aA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVGcwNERZYmhHd2hwSmxt
            WXJsbVVha2N5OW1lY2ExdmRmOFlhVkJMYkRvCmF6dE5xTmdtejhPS3B1cnFIYmlE
            bHg3em45RmZvWDNET1BPTGZTbGpQM00KLS0tIEpIeUsvY2pmT3luVjhUWitndGUy
            K21GQlhFd1BHYXREcU5nQXI4eVluaTgKkEcRn1a7k34frHjl0XzZPyYLZLxCd6NZ
            Ix05TopTdjLXNItXAy1CK19A/YHW586/8WXvoB5DL5k8Bv+8ewO24g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T03:14:22Z"
    mac: ENC[AES256_GCM,data:seNokWaOxVsGYbOraO1xBEs+orMFGFLImLoPKpvIUflrLS2RIQB5zp1r7vBo7HGqHacSMyWMAof8dC2aNtj8+hNFyG0xY/m6TNUemGfAzH+q3+bce/PidnGbTHdVL0LiUFyMhjpOoINgIA159WF4aT9f3+6MBsivsaxLQIY5OaA=,iv:e6lGFW/mk9i79AJlSzDc357Ytb547YSspf0vl4yPi6U=,tag:J8pFFLaRJAxK/jduSw2nMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
