apiVersion: v1
kind: Secret
metadata:
    name: headlamp-token
    namespace: headlamp
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:f1oyGQdCFnuDzSWkMhPRavFbIr+GpXcT37RT5Y8u+8I+vukfWy3BOI1HpeW1op8KHp2I5Fynm01NzPVpOCKrOO+rbdGGZMVJZslxJFqA7kU1yeBgHbATJ7rq3Uuyk7kVrysOdAgSvbqTEtvax6CANKIxsVRkLIYIBvtLZoygbd+PRjYOnBYyS/VxvsNUkzZ2hrlzft/7t2Yl/jXYi0YqFyW3LLEV/auFgG8gz40FeOb9+HzYNjPxz/YTbIT4T4LpQfIpZA6Di3mJEE6zQpbRzvaaT3mQ6itXJkb5ldT5PaGb6q9F8qA4agBp46+otvaDkdpYEFoZB3ezaqHtbPAxYMp5v2kIjcdQQeCS1ZtD59Ad57LeVIKVXYHnMEknT61P2nDLbq9vCUC9BFUDel2xyZ3116a4MI9KiPWB7sOzbzAK7+Uk05PGC8EYIZBBGJXkVygRBJosxtij7M/ofnPE2IRA5vMdFJIAUMiIWKZUzNtTshD5t3URIqe/+cPq8d/4AAWbIS6HxSnoPMfz1f9ikd6q8pzhFJI4u6TxR9PoNM8YwfA6lMU4B1F5y0sDQlQAJKrhiCb8Gv9tm9VOM2DRnM9fPC1108TSlVvoyoH5fKtVvfHInpmQmL3Ccvh2niwzVYERVzbnKSgOPOHvZLA8PKRH6e71rxvQAFtzdSEgt6YgqBl1PGcUGZZuLwMYZHY+Q8QkDt5pKQP//QLF0NWIwMqP7a/odAkRYD6b4eyYvMYZaNc+A7BjkmQdqOr06zNs15zSD/YjEANIL0PA0aVL96Xgr0Xwd0dHSE+XJb8WXSVRttwghZ69LcwxsJNqXRiir8kv4g755s4WRt5DgH7QRB3wMLcWc/DDvSif4xC1lR6d7wakp36KGHXfJCrixmubtlwwVbq7XzL8PLbCT2W7uet5b9lcag0WtvCMvZaIauG/6a58We2QUnCHg/TWef6FX6JSkM/ZOFhxCiQlBm1hh/+L77XPZzvqptyfDq1cM3Xk9EEJ6lPtQZGA7cw7JuxLKGdOU8hwQZkaG7340FbNKW3wFH0kUAIV+xWr8uurHv9ms+6qMCgeKTo/QwnxP86ObI9b4tiMiVIEv9bI5obuvlWECh9AJXUroQ1GrNnKCaWKG3FAq0RW7wWES8UFKrg+qsWWt2DNW0c4V7Hcy/6TX83FljdaT7fF2nCKLLGUY7cawcbGuQVwvLX84/0MfU45ATetBTRnL+2YSFLZOeWq9oJFLSBca9+5silYB/8IzluuvQyzi93/s01wxxoeSj21,iv:PP8SLBnX15g2IIIyfQDyfNewjjIjA+zWPXNknaPpkeI=,tag:mKtNUAEyCcr2acGEwqwseA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU1VLd1R6Sjk4Uk5qSkpL
            ckZaNkhudDVmbDdWeXdqTnBjZVRPTCtrblJNCnJLNS9KTXdTVHp1Q1FHRG9qeUhz
            N2ZPbFpoWWFITkN3UURPOHlXK3p3Wk0KLS0tIFEzcTFFMHZkYldwT3VnZjJlTHBn
            dEVJSEhNV1duK1FLUnA2QUVaVWZKQ2cKbaxK3ZzqbeGEvdRNYGJrd+lS3c0EST0x
            Nlhu/ebIt4CkbfZDNjsVPln5kR0qDM4EWCYUZ7RjlhGnrYd9KPjEOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:58:48Z"
    mac: ENC[AES256_GCM,data:XVtw0SLIzPtGitJlIejr8ln8hJzBQ1IeHI0cwGjO+BkVPyJCrVpHL5H1kdjLaPHkkJycGyhtiz3bYPekfJZP8Elo9RONakOAitW3ZEmMecZA1UIe0CSJcYZAL6OnoBfokdPRXFRFNdLYXDBmbBj/4ASW5sIkDq1F3AWAMlAojQM=,iv:GPOKYzVRv8HkUe3nP6SXFoNAj7PpmivEKkIYPKzopeM=,tag:iSYar5xac+xhpjPCMR2l4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
