apiVersion: v1
kind: Secret
metadata:
    name: headlamp-token
    namespace: headlamp
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ko6aNGKCdZ4q1isNcV/3Fs42nAs+yRNS4f15xFuGx15HeJ4WTDyM2WiA2XwWgpLKqDGqfoE0+7fUt5V+gCRwjhF5b+83oPNe18vy3pcKNjqIoVsMVG3I66wYoH+Abj0t/uFUV47UTHVEDGALfs2/aDnXjXyy/XpAvM1Ijl3kvyqTcT+U0YhKvWUpDLlxTtureDYRYxecLHXjWukWmG6I8puNdqnwUkyVHnta1AoKcOWBpFlvVP3BnlQe5+WKYztR/ebaOQ6wJT7vfllM7+BhltrroNyQ9Ph6Rqb/DlckaIrGbVQw3DaIpTP4OVDMggKVYjwRUSgN60+kDp5ZqQBpdpQYyfCIZyrCARjQBWjfbADhm5tcZjCelMQ9XRX/4Xaidx38JT9k0DBEjQE95jTMAajjS3NVoUiVWS/oINBxOOzkA4DA+4f1C4Fe6CUyoTsgxcCBDUFe3KNdeuISHVAe528wK+QZPwc9ebziXvc+tnhbCtLdAKDOGoF19tWQalKuTlASJzQ54Pr7g7QKN0v8NHoP+37zLECcSCq2bmHDTyn/y8jbxst3fFa+zPdmY2it8l7Q4wcN1LixTBII3mcLu87+vU4xeGaU/dagIe3uIZ5D8Mt1RuseFA+UVt6vjj4HOcwwYWpqNAIuwB3KlrJSQuizl+xZ2mhKiq47EUnLJcqzSJgh8iGTo8uDuQhX89y0EyzNDfDJvvE9NEja7UuipgD0SX3pNnmpIswY9d0sd2ziLUIqNiQTzX1fcoGYwsIcHC3g+Z6KL3oyGzZhUgINIwWLU7Ve9dr0N7Hq/xIXiteF0AfRDix2DPS24LH76p4fehA3dJ9Ur//3WkGgiINVFO1c23MnAobq8kQQ7oqA5waN9llek8YAqYKtrc1alsESpJQ63rsIEHhrshLa6ZuLL5WhyF2aEWuJwL2q+1gKy9NKzYDFtQ7878DAfDrnD0Q3smKDk/8VqscJtmJY6H/v3cg67OMeKc5M98/rou9RZNIuJbS6M8Kv/KeFWafYrpifXBsv3UcyqQpBG58S0VibUlo6yb1BKcyzU08bxQfi0Yg8BJjE9wgS8mMmr6ofGm6r/CvHiAXWI+MHZlx8/d2bQDgJuBQ64clE9BtWQTmnddFIjXWcrAJb7ZX+OJS4UmLBAtA+/IsQJ9e6qEBzN/TcmmcllEqeqxmYQssZFRe1D0uYX6StB5mIWfiJvAK5leNZoAPsxp6VGyFYlltV8Za/GEIA2V+mZ85uF6VOgadirF/CU6Ob+p9xFYs+k+htqa3K,iv:KxSnxM14JmfkhQXZOTKgsSsBjk+EJlAJUSOBfxXiTv4=,tag:IwLmOMG2keKSNTZPt4m2yQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2JRNGFiZitlZHY0djY4
            bkxPV1BNV2hhNEhLTUlxSEY0Y21pazdZVVdVCkROaXd2ZlRBRmRUb20vQUQwOGtY
            YnFQNUNxUjRFQXVNbkJlU29XY01ybVkKLS0tIGVQNU1udVJOWkR1eXZzZzRHVitw
            MDliclR6MVVvUEQxVFAwWmJzVVByR0kKl8dBg6gM5lTvjsg4bEpJl1p7eLQcBeMb
            Mk+ugwhs8kgRTHVi60UbwBifQVes1vCTltEdRhrRKKyI6/oHLq8NYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:43:47Z"
    mac: ENC[AES256_GCM,data:pG9FthCam9cu3P+7NAciEMO/uWtWXfMA+/T71B5WMxoihICJ/rtKkPOqfPCUpEGzvO4G9BEL3r+hJZ3L2cNPRgEJESNnXkr6jQeUPi0RIg5Z2QJ9aIL9gOCaoM6ACriNFuimWCuDudI1LZuOU9ITP0zArMGuch/rdHMLDVHrLR4=,iv:c2gZF+KbPUKTZA8DBYHdcXFiUi0I4Ib7+mZuQPeQUQ8=,tag:3iAixTKGIy05cseUGlZhLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
