apiVersion: v1
kind: Secret
metadata:
    name: headlamp-token
    namespace: headlamp
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:f9BanS2l6/Ule7P577syUCpgJi0Jg+yZ0JXXF+h6+4rP2N8Wv4l37GAF2pTJMdUvcPot5lOabOCqbdTjcfdkUC/0DPQGWmmOgpYlbx/MQ/7hK9DJBzUjgpO4b/UzsR/Z0qoHBknFnCxFJWaIJp+aEdoX5YhbMcS5v7hWM2KJOwL2iO1v3fF+Ug/n/2Yy7pW+ELivyWs7ugt01M8IyISUzJG0XejIvhLnQQWmXaC2tV15dMPADte/glad//9OMnUyy2Su0mu6JbthRGhrWcPfSUW1S15jkOR8PT7jcn6z2K4LNGtw7dcuqjoRzlH6jTzPV7rHQK5lQCvru6RU+lA0U29xuADP3aLjEjDmA6L6HsfXB+wigPHbzBgXD55jeS+aluEYL050g/MugJNTup3PNWCS2pqDYGh82u1xDXF8U+5trKcJT1iqJbB0BqyCYWSHZR+bNOrcbJZ3Q0ne6D30zmFobXhOR0DGh3nJRZOmqP+U0nPz6/EVbNhagKPoOhOtUdD6E2R5Vo40M3Y+2UycjUFOKnRKvNHQfpvoA8Pd5R5BNUOc1xC3fQjZESn4qj9JeC//QoaOxj2avUOnHSJEO5YZnM0bPPsOgjVMV6i6Fcd6yb4cQG8KjyM8dRmORC91slJUlDQjIWjQazSTPo4W8eA/N1Gg+jG0SONT7O2kneTBsxiQNcj4ZULTbRYXFVsdGpy8TYqEDZZtvOivQQwhuPORDtzaZfOMu2tSYOsGC7HN+3EXvJHJBjF8BEP3EiaRywiFq/E4y7s7yb8sppMiK8ivEzhBvEQIT1I4eeuvLCl7Pl5dYbLiucoEGQ4kjrtGo+vpKlSjY6OjbT2zzXzRVCiimHZTIhcAuaE6J6h7PWudpmuujR6YeAj5K0qIDKB5jtYVauDlP+XvG8qA2A/qRT+S/FQ6hVooUWszFqz/fpnnvGt7Extq/qfvWcmhdL+Gk0hdmiklsRRNK1/IgT1/MsRGmVdwx8GPnitS+y4zl2I4ckEeg5krfqg3k253TO2YyzUvhi0/BIQ4lFSZpG+99cAOkcd7FnA7ff+XDo52XzYFUzIFE1Z4ipPZQq4ZFx6lXOtHJiwpaTV6BxFLVxtEdVPdzriACwg716Tt5n+0I3o08THzJmUt2A/ck5yrbv0J4DLeYaVEE3Y7glr0CSPj5YP5xLKUvnU0RaWwpUWSG+1cuFBTs9q/zA6Wsj2yje1iPCgmf8bvlLjrUIbs7gs6AliY7Nty82m7LHY9YL6+7UgrJuW38mXvhrzZwMGAHEPj,iv:1ryDVelvYcH7TUrfqspzZ2Ka3SH7uMMu5Kddkj9RD6g=,tag:cU0CMKYcG8rihTMaDuIqaA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOUxPYys3YldDdHRzN0Fp
            YVZIUXlUaUhqeGF3UGRlOHJ6QmNBY2Z1TkFVClllNnlld2FPaFJESEo1ajdScXNV
            ZDNHQzU1NWMxNS9EcUk1ZFdobGhaS3cKLS0tIHcvaVRjdUZ6em9RQWd1RmxwTWpv
            TnNKWTZJSm96UXEvTEZuejBHZzJBcWcKZOe//r9pTR4EB3crrWyIznGv7GeuMfY7
            7AKjVDG0Os+B7Sz3k+ZIr2Dq1ntRdaWApVcOsoh4pV/TcI2sOVWc3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T17:42:59Z"
    mac: ENC[AES256_GCM,data:bs6q5C/jFMiMGuzlUh8ax5STwEUbQch5VEuEpSHB/WC7snKSAydNu9lKEJMZbaaiQOz/5vIjHfSmSRQI1/wCZ+XKE54vQqBIZikzYy9SjpFViqiAenSQxqaaEtWLVDYr+BZp3YFiZPoXJi8RMPDEXiLu2gF1Hse+UDiy0M0nflw=,iv:yAEkCVrsncpq34d25rKFtyVK6DMFui2uvguMdbqw33k=,tag:j4IbWM5rECzOn48TPF5TRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
