apiVersion: v1
kind: Secret
metadata:
    name: headlamp-token
    namespace: headlamp
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:yJ7L4KFtmP0jIS1MqygoIzyApYiG7bGCe+HaQC8MdagS3G4eEESTe8hl/vG47R0swwmRqawuLA+2Gh3N2JIRp0IkYrfm/jLgTxiN5Y5Em4yRo7OBeXBT/2ZtcbdVZy0lSS+APpRGaT7joSzeygKBMLoD+bki5c6GiOQPpU/yBjAuXsvfHAuaQ4jfGMPmUPfk5hqahnZrj7A4LRKo2htb5e2ve/fYfUUPNnZfxyfskuqJTT29LcSCF0//2jYSIlot9DmBzdAaCvR1i7HN2ORKdkU2e0bG4vJjRqNIMyZzm6a+4YS8sbuzZx8752EVOn4IUU8QGdGwJ4NUO+c2Wj55dAmAR2+saJJtX7mzB9SGTL9CMfl9ynSEfhPJgMJ/IsukZT5lJEFHPfBawk4uJPVZaYQygySvRYK6WNXil/1K6w4VEPzGHz9SHx8dTDkBP0RBpPNQiJ1yrqtlhA1kPS6L8+z1Y/ja5enL7M9mJu7I+Aoy/QQ37FAJXM5/PltpVSfYAnJyntz25Dlfh12HdxLl+SBKeX5uWK8tQ5LSjhA6wwNkEKWTBw/wLRrlqz7JGz9OStpHFiAuFSqjJMOSbcZlEDjnaRLO5yALLykkwJ2iMCAg5gaWM8G8fDg9rSTTdk9W3T+r9r7rxEtBda0nSPo8T8DI03YYI9o6hTFsM4xv58oS3LKTGeQE6BQk9TfO17Y0xycePwsWu8jvaVA508WGAN8gRICIZL5uL2mYOpVHa4tzWHWZO4xrQYbH9x7AUlSGEUsMZzZrSpugSyp0ebHv4pbpopiFFNUTz3YGL0Uhb5/zLaFrNn7wqvw0dVztVtN5393gpdUfJC4lfb3uDekZaADlqv4r3h98IuPyADLOMm2qSvONiDTpWkm7K2F4wZMpt3oRIvm7vA6BN8+UzTi4DivIv8y/1MwmB0DyqlIRpBtoN7ZtaWXPl8ky8SbAL9wt3vEh47+Weg2iqYmEPsFToI+p2zamlU5U8zz3r692MwPA64wKf7Y6L192ORprLdrYoQ9TbfmBf/g6A0ClkeM8x54fXKVM2U7717dZcC0FcsIaHLI0/E5cZF1NW8XSrxvvpUCZ9smrBGCxyGi5ug+XvsDThT0CgAblH/vuJNVR6iQF0xnrjLKmjAQcoz+GlfYXbmxKNEVXJVZeopNl6/QZyvndUp+O7c2vGHnXVANxsj2dJvZaj14drCiWaJ/l9OQcZdrcHSG0XABkNot6HwVjG7Xh/Unj3XaOxNkEMARMiXr5O20yVSp3HaLjPC5mH0rR,iv:xEcDPMbUyELDdLNVhlYIMMC62xadupPpkys2YQN//yg=,tag:y2qp6XgwepT8Q8dMGTeWvg==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdU50Y1RTRnZqeUl0STIv
            dDhScWFid2NpV2NoVkJnSVp5OTZGTERyYkJjCnA5V1dPVmVhdkVpdk5WOTJOZ0li
            UHFHOHNianZjWFgwRUJCOUFPZFE5MkEKLS0tIDhwQ2VwQ3dzSVZlL1IzWSttWnNh
            dk5CTnZKaWoxbDBSYWlFMmRWbWtINjQKoe4Gx2STsJ/Zr3sr7liQfP/cUa0SnPLz
            Hud55FO+wUOgSMtDDSJwCTHf1q8BuvRHGPZQWm1Vo0sOUSKHtzx8jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T21:36:20Z"
    mac: ENC[AES256_GCM,data:wFokNKVGCIfsI4qMVCWoZPkm4YcS+nKU3eZnWi6j2mz6r5Z/RFsexClbhAgxqm39CK2IGfTx2gzhR6csoJ0ql4Vp3MzGdxXjBgmPzajdINuuf5C7Qq/UmxZF5izB4AHWG0ZyahbPi/7127QEnztauIdrzjUyvDzIYnCbHh8a3jQ=,iv:PjzJJPKuq/H1xFZpB+LKFoy0DOLE8vZOiyqLOVKI6G4=,tag:vGQH9OwRGrFD/+NlQo9v2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
