---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netbird
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netbird
    spec:
      automountServiceAccountToken: false
      containers:
        - name: netbird
          image: netbirdio/netbird:0.64.3
          env:
            - name: NB_SETUP_KEY
              valueFrom:
                secretKeyRef:
                  name: netbird-setup-key
                  key: setup-key
            - name: NB_HOSTNAME
              value: "k8s-gateway-router"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RESOURCE
                - SYS_ADMIN
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: netbird-data
              mountPath: /var/lib/netbird
      volumes:
        - name: netbird-data
          emptyDir: {}
