apiVersion: v1
kind: Secret
metadata:
    name: netbird-setup-key
    namespace: netbird
type: Opaque
stringData:
    setup-key: ENC[AES256_GCM,data:Ybozs9xr2vuXzenQ4ug4Ldj06QdUxPK5uO2rqG4kdQn8BPni,iv:EUTEaUZ5l0qF5bmM7PM4Zpn91Kvy7Gt58QSkwQ94/x4=,tag:cHF/Ldx53qdFnJ9fkg6k0Q==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMzBHK0JBTTNUQitoc2Jx
            M0pVb1N5VzE0Z2dJUHR6b3Qrdk5VRGl1TjBnCnlPaC9VbzE1ZXNWVFoxM2VZQnN1
            aENIYUdYSldqK1FHWVNlc2UyT2pPa3MKLS0tIEJDSUprMHdkdkVRL0F2clQxdVJl
            TGlPazhhTEJQM2RLSG1GcWxRbkx0M2cKqI64gg+31K7+blUs3wtnZ2PA/GXivlEf
            XIuudbcxFqBuhkoH5ajP70Rh13/89+qlY69ymbbV5vBvVUQpW+gtdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:58:48Z"
    mac: ENC[AES256_GCM,data:yum3J/bmDPVjsQw2O9PKKHz8HM69JeAnSyGtXkB2QhBfHh1s87yZXRxBHyGTf/BvZ32mBz6n83n/JW5ew3kW3xkyQAmpXpSvshDRGSEs3HloFUbHbbso3kVl7CCaaypihLIrAI5+tPQbumz1ydhehb6gGu1UtIn101XG+uq8f9c=,iv:c/RkuYg9VOz0i/8EA35uKafN+at70GFzr5fhn5MKeFs=,tag:jvCwXbC4cY98vXLzR4JjOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
