apiVersion: v1
kind: Secret
metadata:
    name: netbird-setup-key
    namespace: netbird
type: Opaque
stringData:
    setup-key: ENC[AES256_GCM,data:2U+PmhP8J7LVgAGqHApnsl5aK1/I5XjaIkT6t/VShjqLKCx5,iv:DhimNJaTskeqHga3ieFLMeNbeoa0hjz0/XucmNMEdc8=,tag:Sb1UlgD8lWR76hg/7TY26Q==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WmxkVk5CNzZqbGFESnZZ
            UDFNMVdlVXJqaW9KQTlDV2hXTUg5TTNINUI0CkVlZzM1bTVwM2FIU2NFS1RyRGpK
            TkM3aEREZnltTWZEWk1YYWZLejRhZlUKLS0tIC93a0FDc1JQYjFWcWdDbTlQdnQr
            alNhb2h0UjB5WHpBb3VNVjFpRjBJbVkKX1wKo4NDu4/abjk0sVW7AsjvaM3GjiNZ
            xcaRUPFlsGPSGjC7cvYrq8nqLQPYb7BYrbo1o7XK58yq5CHs+qf43w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:43:47Z"
    mac: ENC[AES256_GCM,data:N4M4Y3x3SUygmlEavAKAeA1Gs/i9+4qUBlLb4f3jQ0nT6k7fIIJxpZRU0igF7sSIF0SFKcW+5YSWpPzqrKe1EsYxS58oLWKgLPMvkMG9HHph5YtkLj4Ep2f6i+ILp6z/ZHVuj+/trWjqkQ7HzhKk8fVWxReTRFJDf8wvcfKBMo8=,iv:3NBcdpo4vWf2/nythSHL6h5eisZ9rJ/OSlSMf/2fHt0=,tag:tpawtO5h4CS531qf4iVT2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
