---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    toolkit.fluxcd.io/tenant: a0d67dc2-fa7f-464f-9521-129316d62d39
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a0d67dc2-fa7f-464f-9521-129316d62d39
  namespace: apps
  labels:
    toolkit.fluxcd.io/tenant: a0d67dc2-fa7f-464f-9521-129316d62d39
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: apps
  name: gotk-reconciler
  labels:
    toolkit.fluxcd.io/tenant: a0d67dc2-fa7f-464f-9521-129316d62d39
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: gotk:apps:reconciler
  - kind: ServiceAccount
    name: a0d67dc2-fa7f-464f-9521-129316d62d39
    namespace: apps
