---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: limboai
  namespace: arc-runners
spec:
  interval: 1h
  chart:
    spec:
      chart: gha-runner-scale-set
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  values:
    githubConfigUrl: "https://github.com/limboai"

    githubConfigSecret: arc-github-token-limboai

    runnerScaleSetName: arc-limboai

    minRunners: 1
    maxRunners: 5

    containerMode:
      type: "dind"

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.334.0
            imagePullPolicy: IfNotPresent
            command: ["/home/runner/run.sh"]
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: "4"
                memory: 8Gi

    listenerTemplate:
      spec:
        containers:
          - name: listener
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
