---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 1h
  chart:
    spec:
      chart: rook-ceph
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: rook-release
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    csi:
      enableRbdDriver: true
      enableCephfsDriver: false
      provisionerReplicas: 1
