---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller
  namespace: cilium
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller-cilium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  url: https://helm.cilium.io/
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  serviceAccountName: helm-controller
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Cluster
    cluster:
      name: devops
    
    # IPAM
    ipam:
      mode: kubernetes
    
    # Routing - Native mode for k3s/kind compatibility
    routingMode: native
    ipv4NativeRoutingCIDR: "10.42.0.0/16"
    autoDirectNodeRoutes: true
    
    # kube-proxy replacement disabled for compatibility
    kubeProxyReplacement: false
    
    # Gateway API
    gatewayAPI:
      enabled: true
    
    # Hubble observability
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    
    # Operator
    operator:
      replicas: 1
