apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:gCbWI0Pl9Eex4ghwG5f1QDDPTCK4fGSp3+Q1kgQS14Ymk5WJkwiJRaPhBvA1PcIaZYrEZy4Pq+Rvz3Tk+ruG8NXzVwggZNBAlYZsFCZa5hdg80B4k0Jm6bwtXhA+LDe755ZMl9s8n8bNwUKxPlJAGKngjBDxflhIOw==,iv:1wvWY+scJg95LGnozmw3jNEAPqCOMtVQTD/PS2AGfmc=,tag:lJ72HGACTJ3S6JwSxZAPrQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y1ZEWEYzc1hZK3laNC9N
            WTFCSGM5NXVKdSsyMTQzb2JXYlhWUDF6UlF3CnYyMC82S284VENCbGZFS1J2UmdY
            WXB3aGdjd3doeHYwV2xzY0wxaTB4OXcKLS0tIDNQejA4dVk0VlNtb0xIbDZNRjA2
            Zlc3cU4rTnVJUGp2SitmS3IwRmF4SWsKqtiWY89FVAqmwnGa/KrP0m/MVJeL9yq6
            ArMW2evyiL+4O1nET0dyQXTnDkkEQvafzHVOuLF1MZkHbb9ipkolFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T17:42:59Z"
    mac: ENC[AES256_GCM,data:TdAj/bzHSG4hukHv/4FVnIwzIwlzuQezLd4Vv8FHdeVLOqOhl+SOc4wiHAyxitGKKY2KmFx+g6Nmlctn7VDV318R4+9LxRE9wDI1iymkbf0F5RAg1aCng6G2pBosuU3qhfodxJbrHA2ZJUbj/9iNUp8ZK088Q8Q2i4sHb6k2Otk=,iv:StwmebpTSzcVnYxaf1lzguMfm3ISIOqocS9NmmUASdo=,tag:zQ/6W8HsOZsus8KNnsxugA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
