---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: apps
spec:
  path: ./kubernetes/apps/dev/debug/podinfo
  sourceRef:
    name: flux-system
    kind: GitRepository
  wait: true
  prune: true
  timeout: 5m
  interval: 30m
  retryInterval: 1m