---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: apps-debug
spec:
  path: ./kubernetes/apps/dev/debug/podinfo
  sourceRef:
    name: flux-system
    kind: GitRepository
  wait: true
  prune: true
  timeout: 5m
  interval: 30m
  retryInterval: 1m