kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devops
networking:
  # Use default kindnet CNI - Flux will deploy Cilium alongside
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    extraPortMappings:
      - hostPort: 80
        containerPort: 80
        protocol: TCP
      - hostPort: 443
        containerPort: 443
        protocol: TCP
  - role: worker
