version: '3'

vars:
  CLUSTER: devops
  GITHUB_USER: stupside
  GITHUB_REPO: devops

tasks:
  default:
    cmds:
      - task: cluster
      - task: flux

  cluster:
    desc: Create kind cluster
    cmds:
      - kind create cluster --config kind.yaml --name {{.CLUSTER}}

  flux:
    desc: Bootstrap Flux
    cmds:
      - flux bootstrap github --personal --owner={{.GITHUB_USER}} --repository={{.GITHUB_REPO}} --path=cluster/kubernetes

  down:
    desc: Delete cluster
    cmds:
      - kind delete cluster --name {{.CLUSTER}}

  reset:
    desc: Reset cluster
    cmds:
      - task: down
      - task: default
