---
apiVersion: v1
kind: Namespace
metadata:
  name: xonery-apps
  labels:
    capsule.clastix.io/tenant: xonery
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: xonery-apps
spec:
  url: https://stefanprodan.github.io/podinfo
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: xonery-apps
spec:
  interval: 1h
  chart:
    spec:
      chart: podinfo
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: xonery-apps
spec:
  parentRefs:
    - name: xonery
      namespace: xonery-gateway
  hostnames:
    - "podinfo.xonery.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: podinfo
          port: 9898
