apiVersion: v1
kind: Secret
metadata:
    name: ui-node-secrets
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3yRm0suvNQWhgmHHfjdF+91A06+DNOJHf1CRV/AB/4JEReorypVLbB+O3NVLKheAOzvA8Egy6C3Xn0T213Sg,iv:LyrIAM3Un/V0xyWSMxK8xx+w6XYGWmQ+8Ky+OagVdwE=,tag:xEHV9n9Nqh5Br9CX8Zjbuw==,type:comment]
    cookie-secret: ENC[AES256_GCM,data:ziNt1KorGmgI3cMSH6PkkaDeYg3boo7kN/8KRl1F7vxYt5I0dORx2SQvn7o=,iv:GVyEHNqcAYEWsj6uIsSYEU0JTSOqY69nJdr8LnrdHG4=,tag:lkkXlxNjfFnqEWUJ5VcCtQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN21QVkFKSkFxKzg0VU1V
            Um5ib2h2eWRzbXVsUUlxNDhZeHFyY1kvSDNRCnVUc3U4WVVETjkzZkJtL3ZFRVdK
            VnhCZ0l2TW1NRnprWlFHQnpBYjJxbFEKLS0tIDZSM0U2SzZNWGNtSFJkaUdzM0NS
            djVKbkd6YmxTZDFFTHZxazZGUVkrRHcKnRI8zipVV5EMdjpYSJE7+/9xVFtM7ebZ
            9acLm4KuuFJCaZ12pnzeCmj6yXN6OxoDXF8VNVRZWA3ik3TOIlq8kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:39:31Z"
    mac: ENC[AES256_GCM,data:Pg9ZIbIBRUq+yBgqOr21gxJHELcQjusC9sp78RUfD6r3ylDSHokSfrVw0XsRM6mdv1Gp5xaDLah66UJfNacQeBqqONGi7azuE7WgT+lB7YbEVj2TI7T8jR/mj+ybtHrudbIHV0bqjFHHhU/F7bjcV/f9RlAS21EfMgjXpuDXJWA=,iv:gxEmZIcHgk42q6y84nHdhVzZ9MZMJx4oDJBD8iLMg7c=,tag:mVq+ZC3EisvY8T/Bfhx5Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
