---
- name: Get k3s version
  shell: k3s --version
  ignore_errors: true
  register: k3s_version
  changed_when: false
  tags:
    - get_k3s_version

- name: Show k3s version
  debug:
    var: k3s_version
  tags:
    - show_k3s_version

- set_fact:
    k3s_installed: "{{ k3s_version.rc == 0 }}"
  tags:
    - set_k3s_installed

- include_tasks: k3s.yaml
  when: not k3s_installed

- include_tasks: k9s.yaml
  when: k3s_installed
