---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-controller-capsule
rules:
  # Namespace management (core multi-tenancy function)
  - apiGroups: [""]
    resources: [namespaces, namespaces/status, namespaces/finalize]
    verbs: ["*"]

  # Core resources for tenant management
  - apiGroups: [""]
    resources: [resourcequotas, limitranges, serviceaccounts, configmaps, secrets, services, pods]
    verbs: ["*"]

  # Network policies for tenant isolation
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies, ingresses, ingressclasses]
    verbs: ["*"]

  # RBAC (full control for tenant isolation)
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings, clusterroles, clusterrolebindings]
    verbs: ["*"]

  # Capsule CRDs (full control)
  - apiGroups: [capsule.clastix.io]
    resources: ["*"]
    verbs: ["*"]

  # Storage resources
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses, csidrivers, csinodes, volumeattachments]
    verbs: [get, list, watch]

  - apiGroups: [""]
    resources: [persistentvolumes, persistentvolumeclaims]
    verbs: ["*"]

  # Workload resources (for tenant quotas and limits)
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list, watch, update, patch]

  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch, update, patch]

  # Policy resources
  - apiGroups: [policy]
    resources: [poddisruptionbudgets, podsecuritypolicies]
    verbs: ["*"]

  # Autoscaling
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [get, list, watch, update, patch]

  # Nodes (read-only for tenant node selectors)
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch]

  # CRDs (for Capsule CRD installation)
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [create, get, list, watch, update, patch]

  # Admission webhooks (for tenant validation)
  - apiGroups: [admissionregistration.k8s.io]
    resources: [mutatingwebhookconfigurations, validatingwebhookconfigurations]
    verbs: ["*"]

  # Monitoring with Prometheus
  - apiGroups: [monitoring.coreos.com]
    resources: [servicemonitors, podmonitors]
    verbs: ["*"]

  # Events for diagnostics
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]

  # Leases for leader election
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [create, get, update, patch]

  # Priority classes
  - apiGroups: [scheduling.k8s.io]
    resources: [priorityclasses]
    verbs: [get, list, watch]
