---
apiVersion: v1
kind: Namespace
metadata:
  name: capsule-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capsule
  namespace: capsule-system
spec:
  url: https://projectcapsule.github.io/charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule-system
spec:
  interval: 1h
  chart:
    spec:
      chart: capsule
      version: "0.8.x"
      sourceRef:
        kind: HelmRepository
        name: capsule
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
