---
apiVersion: v1
kind: Namespace
metadata:
  name: capsule
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller
  namespace: capsule
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller-capsule
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: capsule
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: capsule
  namespace: capsule
spec:
  url: https://projectcapsule.github.io/charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule
spec:
  serviceAccountName: helm-controller
  interval: 1h
  chart:
    spec:
      chart: capsule
      version: "0.8.x"
      sourceRef:
        kind: HelmRepository
        name: capsule
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    manager:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
