---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: net-system
spec:
  path: ./kubernetes/infrastructure/controllers/net-system/ingress-nginx
  sourceRef:
    name: flux-system
    kind: GitRepository
  wait: true
  prune: true
  timeout: 5m
  interval: 30m
  retryInterval: 1m
