---
k8s_server_config: ~/.kube/config

k3s_server_config: /etc/rancher/k3s/k3s.yaml

k9s_installer_link: https://webi.sh/k9s

k3s_server_install_arguments:
  - "--disable=traefik"
  - "--write-kubeconfig-mode=644"
