---
- name: Update and upgrade apt packages
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        force_apt_get: yes
        dpkg_options: "force-confdef,force-confold"

- name: Install pip and required packages
  hosts: all
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: latest

    - name: Install required packages
      pip:
        name:
          - kubernetes

- name: Install Roles
  hosts: all
  become: true
  roles:
    - kubernetes
    - argocd
