---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cloudflared-policy
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  egress:
    # Cloudflare Tunnel connections (port 7844 primary, 443 fallback)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "7844"
              protocol: TCP
            - port: "7844"
              protocol: UDP
            - port: "443"
              protocol: TCP
    # Forward traffic to Cilium Gateway (HTTP)
    - toCIDR:
        - "${lb_ip_pool_cidr_ip}/${lb_ip_pool_cidr_prefix}"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    # DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
  ingress:
    # Metrics and health checks
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "2000"
              protocol: TCP
