apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environment
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: kustomize-controller
  sourceRef:
    name: flux-system
    kind: GitRepository
  path: ./kubernetes/envrionments/dev
  wait: true
  prune: true
