---
- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argocd
    repo_url: "{{ argocd_helm_repo_url }}"
  tags: add_argocd_helm_repo

- name: Create namespace for ArgoCD
  k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace }}"
    kubeconfig: "{{ k3s_remote_kubeconfig_path }}"
  tags: create_argocd_namespace

- name: Install ArgoCD using Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: "{{ argocd_namespace }}"
    chart_version: "{{ argocd_chart_version }}"
    values:
      dex:
        enabled: false
      notifications:
        enabled: false
      applicationSet:
        enabled: false
      server:
        extraArgs:
          - --insecure
    kubeconfig: "{{ k3s_remote_kubeconfig_path }}"
  tags: install_argocd

# - name: Add ArgoCD App of Apps
#   k8s:
#     kubeconfig: "{{ k3s_remote_kubeconfig_path }}"
#     definition: "{{ lookup('templates', 'application.yaml.j2') | from_yaml_all }}"
