apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:hpyvwlyT5UTkhTNd0G1BjUr1Dr5JxD5g5o4/iQaenLICwtR7Nl+XmmJYAjzVjAMimv/aGETTO2JodzdikqePZ6sjetIKGU465aaCfQztpFvzfZJAE/bP+S2vmzUtJTQ8ZsOC8xn+pemA5Y82jX1+UFu8/d3NyU5PLQ==,iv:oWwT1K3r5bpZFGd29onFWU00goUsubGvyGgsRiJ5OdE=,tag:nApGCJRGBSU9xsy/U6SzNQ==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdnA3OGVLc0p4bENuNXJE
            OVJpVHh6RG42OHFSREdHZFliVnZTTGtwTW1ZCmVXS3F6ckNoVTA2K1V6ZUtlM2NX
            TmJxWi9Uc0w1WDZ4cGg2RWxLZkhrbDAKLS0tIEw1Y2VjWnJNaUFzSTdaMGlRSERZ
            TC94MENRYmxwTVFrN1pBVGxXeko1NHcKN494jfqNChHqYiIQanhxWtJLfd8d3UJd
            89JrtK3DdDH+PLh9aaRIwXfzO14waapOqTM4SoPbJHak/BKZLvwNGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:58:48Z"
    mac: ENC[AES256_GCM,data:dFsDjVRju/slrV29uvjbUrFElwEXOBt4Qplcqz9V7t9y6RzdiGbI6GIHOawXlM/CA0DlDwHyz2dQGroYwAr3OEZ7blKdGdxtW4I8DmN2EwxTj3ku64o1U8VyQvfXy3nwOHh9woE2MRn3VRozt3FlL+KSr6m1utRS4vB2FSR1My4=,iv:0JyI74EseiUWsdpEezbRGG0SjkkvrNk2vI2EDz8qWc8=,tag:kO/zl5Y+lLLrU/Sh/l5MHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
