apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:/rYop4Unlm+NbbOBLFbY4IOsvlbEbtLOx56aqxj4Yf/qQgmiH1BPc8I+J2WkOuDgQMtXjpy5IQmy3VKJO7XzI8rUnlXuicwy4G5gC716qWsg9whSVjcuiAFJIcVuXAGDpHh6VuVRBQcbmZCZtIsuIeQeh4hhZK1C9g==,iv:zNWLJVUKqhRd17/hA9VUwQD5lvM8HPPITPNrggL/MDU=,tag:v3d+Hc9p1G18jR+34ohUkA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZEJ5ZENHSWhVUnJIUmFC
            VHNrdVlwdDVtb29oc3NZVm9uY1M5OXNlMWs4Ci9ONVdaMDNMTmswYVBwOVlhVTFv
            TDZ3ZERDSExQaWVpdUIycCtCRlltZE0KLS0tIE5mZnIxV2hZRG5JNjVTdG1yUFpD
            aUN4ZVB3a2hyL09tOW84cVJQelN0OTAKU/jJNQU09upsE73ZVdLBdDORPRD2wX8U
            xlptrfnm/n8HMi32K58bVEbwrdWkSIwTj3ad+wgsa7SY4e+tk8EEZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T20:39:36Z"
    mac: ENC[AES256_GCM,data:tpGAYq0nOZHSNaQMI1cQ8B6KM8Hs6a4w5MNlzXcY2BfMGL0/cBYp6lvB1wN07G9X+Y94iwRvLnKzel24g/ByflzLMYWSMF5obfmJkmBCjdGiB3mAK4HN4LLCKmXKVl5kK2uTYhqEFvqdMo1V+yFOPeUFO306u8EFs3UARbfYvlo=,iv:AMPmq3gAoDE076Hf15UmIZc4UrT1R84MG5vljYdDfxM=,tag:dJOhED78i8N+2mXzUoDq2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
