apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:tvGioWvNWmYqeGQt8+bOqgggiNsJ8fj0m2HWFKJcbJcEhStKrRMcvBRCl1DOybVlNAwQotX1OXJF65+l+t9ri3JbWQcvYYzOnv0bjO/NPCAMab8cHYoiTF6FXijVToFMQYDxzBlNenlmpX/qDd6jocvTivAaNjLMJw==,iv:DT5X3eU486sCjocUqnzBFKQdtpiwG9mYcxFD6+lIwOU=,tag:G84UGtepn5OIXZ8eNBVTPw==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWHA4cURHR1M2ZkkrVlZh
            U3VPSHlpSDRxaU1mYkR0V3djZG5KY1A2L3lNCnJMRlJzNGZFZjlLK3ZwWFliaVJm
            WjlxOXFQYVNYZVFSek1sSGZwdE1wekUKLS0tIG1YV0s3OExVOFpUdVRFSEs4UlRm
            N1ZtVmxpYkZDYW45Y05KK0g1R1IvVmMKheN7i6u5D0xVQARioFB0tOZ9l8J8Om7x
            fcLkFH0c5s3eutJAWe1NK9Hzx2bbSebKFdVr1VU6iYGGlTXy4z44ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T19:43:47Z"
    mac: ENC[AES256_GCM,data:TOfMkrmX0L1G1iNnAx8DaCDQnnTZn7brzCrT62OpcogcXuWX2OKkZFpMo8eHSr9zgwAbns5GgwYyptjhMWQxk703D71W87CsH26ghJzEGumUiYCuOykLaoy2wBL3/8AwyU+F5CzJ7MhsE1gjBOqnUpkgvGKE9zl4CfUGY4ra7c4=,iv:wSEheWFwtdy2CwgOQAwo8GdMJ7xhh0kqX73FZ0Jr/as=,tag:U/39K5w9nXKa2zyOE37qzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
