---
- name: Init K8s
  become: true
  block:
    - name: Check if K3s is installed
      ansible.builtin.command: k3s --version
      register: k3s_version_output
      changed_when: false
      failed_when: false

    - name: Set K3s installation status
      ansible.builtin.set_fact:
        k3s_is_installed: "{{ k3s_version_output.rc == 0 }}"
      changed_when: false

    - name: Download K3s install script
      ansible.builtin.get_url:
        url: "{{ k3s_installer_link }}"
        dest: "{{ k3s_installer_path }}"
        mode: "0755"
        timeout: 120
      when: not k3s_is_installed
