---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  url: https://helm.cilium.io/
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.17.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cluster:
      name: devops
    ipam:
      mode: kubernetes
    routingMode: native
    ipv4NativeRoutingCIDR: "10.42.0.0/16"
    autoDirectNodeRoutes: true
    kubeProxyReplacement: false
    gatewayAPI:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    operator:
      replicas: 1
