---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.x" 
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true

  values:
    # --- K3s Integration ---
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true

    # --- Native Routing (Optimized for WiFi/Pi) ---
    routingMode: native
    ipv4NativeRoutingCIDR: "10.42.0.0/24"
    autoDirectNodeRoutes: true
    
    # Cleaned up endpointRoutes structure
    endpointRoutes:
      enabled: true

    # Dynamic interface detection (covers WiFi and Ethernet)
    devices: '{eth+,wlan+}'

    # High performance load balancing (preserves Client IP)
    loadBalancer:
      mode: dsr

    # MTU 1500 is safe since we removed the VXLAN tunnel overhead
    mtu: 1500
    
    # --- IPAM & Outbound Connectivity ---
    ipam:
      mode: kubernetes
    bpf:
      masquerade: true
    enableIPv4Masquerade: true

    # --- L2 / VLAN Compatibility ---
    vlanAllowAny: true
    externalIPs:
      enabled: true
    l2announcements:
      enabled: true

    # --- Features & UI ---
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "k8s-co-il-pool"
  namespace: cilium-system
spec:
  blocks:
    - start: "10.10.10.240"
      stop: "10.10.10.250"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: "l2-announcement-policy"
  namespace: cilium-system
spec:
  interfaces:
    - ^eth+
    - ^wlan+
  externalIPs: true
  loadBalancerIPs: true