---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 30m0s
  targetNamespace: metallb-system
  serviceAccountName: kustomize-controller
  chart:
    spec:
      version: ">=0.14.x"
      interval: 12h
      chart: metallb
      sourceRef:
        name: metallb
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    crds:
      enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
