# Encrypt with: sops -e -i secret.yaml
# DSN uses postgres admin - password must match database/postgres/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kratos-secrets
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:urp1YiwqGKXfAUBDMjzknWMmtsjOAPHZBLtk5XwdJadS5Rvczis=,iv:uvpYB/nW+R+qMcpE/Mr1PaxrBkYzcNv5m2/qf6VnPTY=,tag:8BfhwEjOAqa+n7/qgGv2xQ==,type:comment]
    dsn: ENC[AES256_GCM,data:/8R+rkDMrHe2zr+eoQbKy/wol3ps/Ci8V7WAbMwgqYvpUgBsX8+GR/GbgndBwhOaZAzyzkKpL6g0MWd2XpCyN2F6YSO+1JvBAZu8U3jKEn3jV0NkXRon6oy+Wm8NXdPrsKSDgHWfzbe+PecgS/+LTQe1ozkUtOkyNMFssnlnSg6RdbS9eleH3Qa5zstxAATgUG7ahqODxrViufwL7g==,iv:bwCvUgtGY/wXIaG8Jv7pSbIca3I21+AWNfXXgQ1vpUk=,tag:Cvr3jvZeN00bXREIuJbgAA==,type:str]
    #ENC[AES256_GCM,data:1d/XFwnNmpHljZKGq23s,iv:rirX5diXTetTmAMC1RubOMiUd3nMEhgcGVB+i6CV30Y=,tag:FDvRxp5L7gzRCBxf5fglDg==,type:comment]
    #ENC[AES256_GCM,data:L7cuE4ymkf52OjxrNN2yJuLDh09KrvlA0UKZI2Rcy0gHn6RXttWuHSyO2tSpIg20299PFFWWdYfU,iv:a+XbMisqEHGTtyqqoWBBTn2qw09ro8nN9UfRaHQJsNU=,tag:ulr/UUi+dznuhaFX9PDhzA==,type:comment]
    secretsCookie: ENC[AES256_GCM,data:0XJG4byDhvDQcMyRzDVsOjANeTCZdUtzCiWqeOXxOFNdF/IaQZyS9F+xM08lareHxbEsXyya388v8zCTL6S/ag==,iv:PP3JkeTlPLufAxKAb7SonyuLxZIJ65lEaZjk375mAFY=,tag:QL7Py9Dv9TqfnaMXDNre0Q==,type:str]
    #ENC[AES256_GCM,data:R53PSN7QW5zOrn1MQ7/ptjUk1ALvGwYoYo5zLwGW+bAqrZtQxbO8nMpZv+11asym+F1xKypD3bfKh6qdsmGQTV9xH8H6wlpnYGV6,iv:8H63qDMDJiH2UpNxG3WgRB8RyzDXuJ0REdya3tixQ8o=,tag:bmqiv3jtRYwsu9wO5dKuhQ==,type:comment]
    secretsCipher: ENC[AES256_GCM,data:bSyDGiuEXAeadLjsSqVxJKeGQbc4Ibwq+gljedrgrg4=,iv:q7ax/g5SYl8F/GX5n1OxPrGdvN41T8r5zl+xmb8/uWg=,tag:4Uy/noywRLIPsQjV6KlyWA==,type:str]
    #ENC[AES256_GCM,data:qizVIno0x0e5zmoveF9VU/qtoALeuwtfUeBOPSfXWzB2hlCbDkVbC3U+4go7BIc=,iv:AvSWmIJ4Ip7SWzVOzmMfMzrgEy0zX+wbVBwiC9+hjfo=,tag:meHW+inTQrxwpYvhS+Z6fA==,type:comment]
    github-client-id: ENC[AES256_GCM,data:uS/QvCoOCJHIPxa8Qyf5LdBwH94=,iv:3K+UOqlmpIfrKJLD1Jvm0UHOzKfhiUiNCdpveyg2mDo=,tag:fG8l2o29px83fapZrxQajA==,type:str]
    github-client-secret: ENC[AES256_GCM,data:IyRoN4Vz+Pg+EgsyXXqrfXzkbPOu9B+OYPnvE+FqVaif+W7rbRkw3Q==,iv:PF8HBL3aNDUW8VwILssJfePrOqvmcJircTYznwKJbuI=,tag:YXY8c0VhchOq1ebgcg/SkA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ0dobW1iWCtSaGhXNitr
            UWVRK1VQWHMvekdaVkticmZDVFNhNXhsVWgwClMyUTNBUUppSi84dEczcXBGNk1S
            dzg2UUw2OXdSbUNlbjNIRnRPL1IzT0EKLS0tIHhjWTFLN0w3UW12YlhKLys0T0Ji
            TWtvWWtqakVPUm1LWE9SOGNISjJISFUKOi7RUgEOTSKCKUR8hhTN1V2+WY823+fU
            NEwNGZ+4vf+3G3WkhK6k0kRPSFmZ9H/g57dZtpm5LavkGkqTy8b/Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T13:11:08Z"
    mac: ENC[AES256_GCM,data:7ln4CaAiyDhKZhtMD12jLDAt9o7Ymq/9DPAP4fisdMBKBORUTfc0Imr4C0JDfZ7vscSzIGo+Ip7qPE8bCoGJymapcj7HvjlSOrSHPc1L6C2Tbj5wQ2BRmmWxHT32OXn+TznTtmstNeRGoGDW2MnXhe7YUUpwCvcF5FdXHkNOt7E=,iv:tH3y4STIgkVeznbWA3XfbF+Zej3IL+BRocdF9Cg0s3w=,tag:w6xc50HYPrddz2miCg7wmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
