# Encrypt with: sops -e -i secret.yaml
# DSN uses postgres admin - password must match database/postgres/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: kratos-secrets
    namespace: ory-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lRjIqphpk6UJxZBIqHWPbqxPGZervuHcrfB7ajl8rmOrVFWT6Zw=,iv:+or7dDon57uKmTPOKAd0KzKIl8la73PfamEfH2JNJGI=,tag:uab7/zeJ6NkUQZT2JrB3dQ==,type:comment]
    dsn: ENC[AES256_GCM,data:cYc1nKzavzU/AVy/Wyk7RYTAWDXakqiQHa6QZ8kwhS7aUEVsDRYLKd2orVaiaVUpC5nUBb0lzBrK8/W0Kj33I8qVSnZwGbvxSWKUYpooEyv3rwozVE9paMdPWIYZ3VWRiwo+cHJs+YusXXc1qm4iOVvJfahn2FSRouQBuPUbhcY2Babqndvy6f49yg==,iv:M1AncpXb4tC91BXV+WWL4NuSDByKi89WfJykfw8o4fk=,tag:+Z+N536LMeTQ/1vl4WL+MA==,type:str]
    #ENC[AES256_GCM,data:kKxy+YMrtx8xbAppTbM7DxsOkqL1h23TNlVI3eKkIV6eW2+I/OQ58wZjMp0fuyG+Woh3d2c=,iv:rbL5h1/wxYvTsQS6swU+cqwNMhVYrQDgEnw+inZJaIA=,tag:hRON9UrS2mL9dRf3cJP3Dg==,type:comment]
    secrets-cookie: ENC[AES256_GCM,data:3cbzD/CbweUr31qjoapkuHZrUY2bRut2c28Ebg2h++EFDbOcPVE3QoGbwoRo01Qm45wWs4McnzrEDslpNE0nyA==,iv:m6n3S7mrZ9UxaQsQWcxVQA6QH/bUYS/7adPItxhjAnI=,tag:VMWB6cW+KWSjFpDLyZN8/g==,type:str]
    secrets-cipher: ENC[AES256_GCM,data:WPBNZQqmj4r4/9V3s1eSHjv7WjaopVDnLF1PQ2hyaj81N1Lb1+j2mExkjiWRa3z70gC4HS1ttKHoWoEIlHLi4g==,iv:jmuWU3SEWNPg7kOxUckxJzcbdzt/AMbRrS25eo9TmE8=,tag:zhgvDoGECObWOlVpSQRWpg==,type:str]
    #ENC[AES256_GCM,data:YpfhlneE4VHdVAZF0tfa5j6wBiqP1cIBBnMB/dp3lZblVro+HEVrCsxNqAzg3P4=,iv:RECf5g/meGy2vpR9FiFgcLa15zS0COIqrDqiWKgdrBg=,tag:ykOqvqrfVqxecf0lB7Dsbw==,type:comment]
    github-client-id: ENC[AES256_GCM,data:/Ubl8WMkVem4asA1DMlce48xjII=,iv:VXbj3nRYKYcejooEqdA5/7uBKv3pkeDWmGIxD4KxcG4=,tag:MyrOaULrF+07jwPMt3A8Jg==,type:str]
    github-client-secret: ENC[AES256_GCM,data:n9AZPX0n7pWHzWl4LLWK2CBmJAptrUAEpmBGYjpFcVp8zemyAeBicQ==,iv:FZTJ1LvqkGHs+UOIIbKVxr/2OrRtcoxLMC/Nt3810z4=,tag:Dl0/WQNhtXIoCXGP5VKseA==,type:str]
sops:
    age:
        - recipient: age1rh4am6rddevkvu5wkq4rzev7h7apndycak7zhy3vkryct4awza6qh7t2a2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEazF5dVU5MU1wRyszQnVs
            dFUydTlNcjBsUHlCcmtjTlUwY3UwOHFiTm1NClFRWDBuZThwTGxVdDRuWW5UYkpu
            eUZoTmJ3ZnFHSGJPK0hJQkVYWlVhS0kKLS0tIGdhOHdObXBzVmYxeTZPdU5LQWV0
            aVV2Q0svTHBqYUh5UEtCOXR4eHV3TXcKaoi9id6we5ZsWBGOc2+ArdtL/sWItXbJ
            JpCSvEx7XuslIbx/Zub5gvt/Y4jpAHAQ9P6pABH4DYlnK1L8/bzi7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T00:21:31Z"
    mac: ENC[AES256_GCM,data:qhMlK2ZX3iVlw6EsKhiSCbWzgKRev1Lmfx+tQaQcXrlaMKsA5oKVKes0LjnuPIL0bjUvXyYiQLN0hNQ7ChpSXUMCWkva/36oOmEI4v97DP4SaP3fdPB++mdB+k7nEB7iUcb7+/8P0DTQuoCFWEd1/pqanYkKRxohudtsiFWBIjk=,iv:nm/zIXFR2M4PXyZ4M5og0aUa9zNenPZ4urwD9dQeal0=,tag:oyzgqKtO0ranAelv/q8Vvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
