---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: net-system-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/infrastructure/controllers/net-system/cert-manager
  sourceRef:
    kind: GitRepository
    name: my-repositories
  wait: true
  prune: true
  timeout: 5m
  interval: 30m
  retryInterval: 1m
