apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned
  namespace: xonery-tenant
spec:
  isCA: true
  secretName: selfsigned-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "*.xonery.dev"
  dnsNames:
    - "*.xonery.dev"